### ISSUE TITLE
Block smoothing applied inconsistently

### ISSUE THREAD

**Issue by kornelski** [libjpeg-turbo/libjpeg-turbo#343] opened 2019-03-19 17:55 UTC
Given this image (which uses nonstandard progressive script to demonstrate the problem better): 

![b](https://user-images.githubusercontent.com/72159/54629363-56d2ed80-4a6f-11e9-89e4-d48f36560e22.jpg)

If you decode the first 8000 bytes, it looks like this (no smoothing):

![a-8000-turbo bmp](https://user-images.githubusercontent.com/72159/54629418-72d68f00-4a6f-11e9-91b0-6c17ef638342.png)

And if you decode the first 8100 bytes, it looks like this (smoothing kicks in):

![a-8100-turbo bmp](https://user-images.githubusercontent.com/72159/54629438-7cf88d80-4a6f-11e9-9056-48045c5f6b1d.png)

But if you decode 12000 bytes, it looks blocky again (a bit more data at the top ~~disables~~ visibly reduces smoothing for the entire image):

![a-12000-turbo bmp](https://user-images.githubusercontent.com/72159/54629515-a1ed0080-4a6f-11e9-93a6-edc7df75ac2b.png)

So block smoothing kicks in only in specific case, temporarily. Visually, unsmoothed DC is very undesirable. It's also problematic that arrival of new data, even if the next "layer" is incomplete, disables smoothing for the area of the image that has less data.

Ideally, the DC-only (or almost DC-only) blocks in the first and last image should look similar to the smoothed blocks in the middle image.

**Comment by dcommander** [comment] 2019-03-19 18:28
Does libjpeg also do this?

**Comment by kornelski** [comment] 2019-03-19 19:21
Yes, it's a very old bug inherited from libjpeg.

**Comment by dcommander** [comment] 2019-03-19 19:34
Does the newest libjpeg code also have it?  The reason I ask is that Guido made numerous modifications to the DCT algorithms, and I'm just wondering if this got fixed in the process.

**Comment by kornelski** [comment] 2019-03-19 21:03
Yes, v9c (shipped with macOS) has this.

**Comment by dcommander** [comment] 2019-03-19 21:11
Has the bug or has the fix?

**Comment by kornelski** [comment] 2019-03-19 21:30
Has the bug.

**Comment by dcommander** [comment] 2019-03-19 21:52
OK, well, my next step would be to look at the image closely and try to figure out whether libjpeg-turbo is disabling block smoothing for some legitimate reason:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/jdcoefct.c#L351-L400

**Comment by dcommander** [comment] 2019-09-24 18:37
@kornelski Please post the scan script you used when reproducing this issue.  Thanks.

**Comment by dcommander** [comment] 2019-09-24 19:40
Bearing in mind that I haven't tested with your specific scan script because I don't have it, this is what is occurring, as far as I can tell:
* Block smoothing is enabled or disabled based on the scan used in the output pass, which is the last scan that has been successfully decoded.
* When the entire image is decoded, block smoothing is disabled because the `smoothing_ok()` function detects that block smoothing is not useful for Scan 9.
* When 8000 bytes are decoded, block smoothing is disabled because Scan 3 is cut off before the quantization table for the Cr component can be read.
* When 8100 bytes are decoded, block smoothing is enabled because the aforementioned quantization table has been read, and `smoothing_ok()` determines that block smoothing is useful for Scan 3.
* When 12000 bytes are decoded, block smoothing is enabled because `smoothing_ok()` determines that block smoothing is useful for Scan 4.

AFAICT, libjpeg-turbo is behaving properly in this regard, and the phenomenon you observe is due to the data for one of the scans being incomplete.

**Comment by dcommander** [comment] 2019-09-24 19:49
If I understand your original post correctly, what you are suggesting is that libjpeg-turbo should still enable block smoothing even if the scan data is incomplete.  However, it can't do that without a complete quantization table, since the smoothing algorithm must refer to that table.  Probably the best I could do is to modify the behavior of the library such that it enables block smoothing on a component-by-component basis rather than on a scan-by-scan basis, but I'm not sure if that would be any more visually appealing than what the library is doing currently.

**Comment by kornelski** [comment] 2019-09-25 11:19
The main issue I have is that bottom of the image looks worse (less smooth) at 12000 bytes than it does at 8100 bytes.

Is it because the new scan data makes smoothing less aggressive for all of the image? Could smoothing strength be adjusted in the middle of Scan 4, after Scan 4 data ends, and do the same strength of smoothing as Scan 3 for the rest of the image?

**Comment by dcommander** [comment] 2019-09-25 15:12
OK, I'll see if I can develop an understanding of why that's happening.

**Comment by dcommander** [comment] 2019-09-28 21:49
@kornelski I cannot proceed unless you provide your scan script and the source image.  I need to experiment with producing a JPEG file containing only some of the scans in the file you submitted.

**Comment by kornelski** [comment] 2019-09-28 22:10
IIRC this image has been generated by MozJPEG which selects the scan script itself. 

```
0: 0-0, 0, 0;
1: 0-0, 0, 0;
2: 0-0, 0, 0;
0: 1-8, 0, 2;
0: 9-63, 0, 2;
0: 1-63, 2, 1;
0: 1-63, 1, 0;
1: 1-63, 0, 0;
2: 1-63, 0, 0;
```

**Comment by dcommander** [comment] 2019-10-03 22:33
Through the magic of scripting, I was able to determine the break points in the first four scans:

| Byte Count | Notes |
| ----- | ----- |
| 1-213 | Does not decode |
| 214-6105 | Partial decode of Scan 1 (Y: DC) -- no block smoothing because Cb quantization table hasn't been decoded yet |
| 6106-6124 | Does not decode |
| 6125-6132 | Partial decode of Scan 1 (Y: DC) -- no block smoothing because Cb quantization table hasn't been decoded yet |
| 6133 | Full decode of Scan 1 (Y: DC) -- no block smoothing because Cb quantization table hasn't been decoded yet |
| 6134-6141 | Does not decode |
| 6142-8018 | Partial decode of Scan 2 (Cb: DC) -- no block smoothing because Cr quantization table hasn't been decoded yet |
| 8019-8037 | Does not decode |
| 8038-8045 | Partial decode of Scan 2 (Cb: DC) -- no block smoothing because Cr quantization table hasn't been decoded yet |
| 8046 | Full decode of Scan 2 (Cb: DC) -- no block smoothing because Cr quantization table hasn't been decoded yet |
| 8047-8054 | Does not decode |
| 8055-9959 | Partial decode of Scan 3 (Cr: DC) -- block smoothing applied |
| 9960-9978 | Does not decode |
| 9979-10015 | Partial decode of Scan 3 (Cr: DC) -- block smoothing applied |
| 10016 | Full decode of Scan 3 (Cr: DC) -- block smoothing applied |
| 10017-10024 | Does not decode |
| 10025-28282 | Partial decode of Scan 4 (Y: 1-8 AC) -- block smoothing applied |
| 28283-28301 | Does not decode |
| 28302-28356 | Partial decode of Scan 4 (Y: 1-8 AC) -- block smoothing applied |
| 28357 | Full decode of Scan 4 (Y: 1-8 AC) -- block smoothing applied |

* Depending on how many bytes you decode, it isn't guaranteed that you'll successfully decode the image at all.  Deterministic behavior cannot be guaranteed unless you decode full scans.  Otherwise, you're basically dealing with a corrupt data stream.
* Mathematically, block smoothing is applied to Scan 4, but as near as I can figure, the visual difference you observe is due to the algorithmic difference between smoothing only DC components and smoothing DC and AC components.  (Probably for performance reasons) the smoothing algorithm doesn't bother to smooth the underlying DC components from Scans 1-3 once Scan 4 begins, because Scan 4 will eventually overwrite those pixels.

At the moment, this still appears to be expected behavior rather than a bug, and I have no idea how to make the library behave otherwise.  I don't understand why you can't decode full scans, thus eliminating this problem.

**Comment by kornelski** [comment] 2019-10-04 11:22
* Decoding doesn't have to be guaranteed. That's perfectly fine. I'm concerned here only about results that do appear on users' screen.

* I agree with your assessment. Initially I assumed that smoothing wasn't enabled, but it is enabled. The actual problem seems to be in the strength of smoothing of scans that have incomplete data.

Even tough it's not strictly speaking a bug according to the current implementation, I think there's a room to improve. 

The problem is that data from Scan 3 looks smooth before Scan 4 arrives, and starts looking more blocky after Scan 4 starts, but before Scan 4 is fully available. Purely from visual perspective, this doesn't look right. It appears to regress from smoothed image to almost-not-smoothed until data from Scan 4 covers it up.

I agree that decoding of only complete scans would be an OK solution. However, I think currently this would require libjpeg-turbo users to change their implementation to achieve that. libjpeg-turbo will decode as much as it can from the available input, so the caller would have to be careful to pass specific amount of data to the library, and no more. I don't see an easy way to do this, so I don't think I could convince browser vendors to do this with the current libjpeg-turbo.

Would you be open to adding options/functions to aid decoding of only full progressive scans? I'm thinking about something that only needs few lines of code changed for users of libjpeg-turbo.

I think it would be a valuable addition if it also improved performance. Currently browsers re-render images whenever new image data arrives. If they could re-render image only when full scan data arrives, that would avoid the smoothing problem, and reduce number of re-renders they perform.

**Comment by kornelski** [comment] 2019-10-04 13:13
Alternative solution, which would be my preferred one:

* When decoding Scan 4, compute how many lines (or MCUs/lines of MCUs) are available in Scan 4, and smooth with Scan-4-strength only these lines. 

* After running out of Scan 4 data, smooth the remainder of the image with the settings/method that was used to smooth Scan 3. 

So that data from Scan 3 that is not covered up by Scan 4 data remains smoothed the same way it was before Scan 4 started. 

Some inaccuracy on the boundary is fine (it seems reasonable that switching smoothing modes can't be done exactly and it may be delayed by block or MCU height)

**Comment by dcommander** [comment] 2019-10-04 16:30
> I agree that decoding of only complete scans would be an OK solution. However, I think currently this would require libjpeg-turbo users to change their implementation to achieve that. libjpeg-turbo will decode as much as it can from the available input, so the caller would have to be careful to pass specific amount of data to the library, and no more. I don't see an easy way to do this, so I don't think I could convince browser vendors to do this with the current libjpeg-turbo.
> 
> Would you be open to adding options/functions to aid decoding of only full progressive scans? I'm thinking about something that only needs few lines of code changed for users of libjpeg-turbo.
> 
> I think it would be a valuable addition if it also improved performance. Currently browsers re-render images whenever new image data arrives. If they could re-render image only when full scan data arrives, that would avoid the smoothing problem, and reduce number of re-renders they perform.

For more than 20 years, the libjpeg API has had functions available for doing exactly that, as well as documentation on how to use them to achieve exactly what you're proposing:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/libjpeg.txt#L1937-L2298

**Comment by dcommander** [comment] 2019-10-04 17:13
> * When decoding Scan 4, compute how many lines (or MCUs/lines of MCUs) are available in Scan 4, and smooth with Scan-4-strength only these lines.
> * After running out of Scan 4 data, smooth the remainder of the image with the settings/method that was used to smooth Scan 3.

I'm not sure whether that's possible.  The smoothing algorithm is applied on a block-by-block basis just prior to performing the IDCT on that block, and the values used for a particular block depend on previous blocks.  I traced the code at a very fine-grained level, comparing the behavior between 10016 and 10025 bytes.  It appears that the differences in the smoothing coefficients begin at the first block and propagate down from there, which suggests that there isn't a "scan strength" per se.  The scanning algorithm is applied the same way in both cases.  It just produces different mathematical and visual results based on whether the first block of DCT coefficients from Scan 4 has been decoded or not.  When decoding a progressive image, the library is automatically operating in buffered image mode, so each scan is entropy-decoded into a DCT coefficient buffer, and the IDCT is performed on that buffer after all available input data is decoded.  Thus, the only difference between the DCT coefficient buffer when 10016 vs. 10025 bytes have been decoded is that the first block contains some AC coefficients in the latter case (from the first block of Scan 4.)  Thus, those AC coefficients are wholly responsible for the differences in mathematical and visual output.  It may be possible to detect that a scan is incomplete and restart the smoothing algorithm (i.e. clear any mathematical dependence on previous blocks) in the block row immediately following the incomplete scan, but that may not visually be the best thing to do in all cases.  It is the best thing in this case only because the preceding scans are DC-only.

Another concern I have is that the smoothing code derives from the JPEG standard itself (Section K.8 https://www.w3.org/Graphics/JPEG/itu-t81.pdf), and the libjpeg behavior has been constant for so long as to become canonical.  Extreme care would have to be taken to avoid unintended consequences.

The buffered image mode described above was always intended to be the solution for partial decompression of progressive images, and displaying incomplete scans was never intended in the design of libjpeg.

**Comment by kornelski** [comment] 2019-10-04 17:51
Thanks for the pointer to the docs. I've seen it before, but I haven't fully understood it, as I didn't think it was enough to implement whole-scan-only rendering. 

Do I understand correctly that to implement whole-scan rendering you'd count how many times libjpeg reported `JPEG_REACHED_SOS`, and then call `jpeg_start_output(…, n-1)` to render up to the previous can? Or even, can you call `jpeg_start_output(…, cinfo.input_scan_number-1)` to accomplish this?

**Comment by kornelski** [comment] 2019-10-04 17:55
> It may be possible to detect that a scan is incomplete and restart the smoothing algorithm (i.e. clear any mathematical dependence on previous blocks) in the block row immediately following the incomplete scan, but that may not visually be the best thing to do in all cases. It is the best thing in this case only because the preceding scans are DC-only.

That sounds very promising. It may suffice to limit this only to the case when the previous scan is DC-only, because differences between later AC scans are not so strong.

Is it hard to implement this? Could you try implementing/prototyping it to see what are the effects of this?

**Comment by dcommander** [comment] 2019-10-04 19:39
> > It may be possible to detect that a scan is incomplete and restart the smoothing algorithm (i.e. clear any mathematical dependence on previous blocks) in the block row immediately following the incomplete scan, but that may not visually be the best thing to do in all cases. It is the best thing in this case only because the preceding scans are DC-only.
> 
> That sounds very promising. It may suffice to limit this only to the case when the previous scan is DC-only, because differences between later AC scans are not so strong.
> 
> Is it hard to implement this? Could you try implementing/prototyping it to see what are the effects of this?

I think I was able to achieve the desired result with the attached patch.
[0001-Decompressor-Fault-tolerant-block-smoothing.patch.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/3692045/0001-Decompressor-Fault-tolerant-block-smoothing.patch.zip)

Minimally, however, this would need to go through a beta cycle and further testing before I am confident that it is regression-free.

**Comment by dcommander** [comment] 2019-10-04 19:49
> Thanks for the pointer to the docs. I've seen it before, but I haven't fully understood it, as I didn't think it was enough to implement whole-scan-only rendering.
> 
> Do I understand correctly that to implement whole-scan rendering you'd count how many times libjpeg reported `JPEG_REACHED_SOS`, and then call `jpeg_start_output(…, n-1)` to render up to the previous can? Or even, can you call `jpeg_start_output(…, cinfo.input_scan_number-1)` to accomplish this?

Referring to the documentation section I linked to earlier:
```
 jpeg_start_output(&cinfo, cinfo.input_scan_number);
```
is the correct way to accomplish this.

**Comment by dcommander** [comment] 2019-10-07 22:58
@kornelski I am waiting on you for two action items:

1. Clarify whether full-scan decoding is a possibility, which would obviate this issue.
2. Test the patch I included in the comment above.

**Comment by kornelski** [comment] 2019-10-08 20:51
The patch is great! It neatly solves this issue.

As for decoding of whole planes, I'm still trying to reach out to browser devs to get feedback on this, since it's not my decision to make.

But I think the patch is still good to have, as it solves the visual glitch for apps without them needing to change their implementation.

**Comment by kornelski** [comment] 2019-10-08 23:04
I'm reaching out to browser vendors to get them involved. 

* I'll suggest that browsers shouldn't render DC scans with a missing chroma channel. This gives wrong colors (green faces problem I linked to in previous comment), so it's best to wait until all DC channels available. That will also ensure that DC is always smoothed (with or without this patch).

* I'll ask about rendering of complete scans. I'm not sure how much of the current browser implementations is accidental and what is intentional. Consistent visuals and improved performance are a plus, but OTOH all browsers render incomplete scans, so maybe that is important for them to show loading progress and show as much of the image as possible. If they want to show incomplete scans, this patch will be useful.

**Comment by dcommander** [comment] 2019-11-07 21:20
Patch has been pushed to the dev branch.  After a more thorough code review, I don't see any issues with it, but please let me know if you encounter any.

**Closed** 2019-11-07 21:19 UTC
Labels: enhancement, implemented

**Comment by dcommander** [comment] 2019-11-08 18:47
I did discover an issue when the patch is used with arithmetic coding.  Investigating.

**Comment by dcommander** [comment] 2019-11-08 19:05
Ugh.  Well, the arithmetic decoder unfortunately doesn't have the mechanism for detecting incomplete scans.  If you don't care about the arithmetic decoder, then I'm fine with making this feature Huffman-specific.

**Comment by dcommander** [comment] 2019-11-08 19:46
At the moment, I can't figure out how to make the enhancement work with the arithmetic decoder at all.  The arithmetic decoder doesn't consider hitting an unexpected marker while decoding a scan to be illegal, so any state that is encountered with an unexpected end of scan will also be encountered with a normal end of scan.

**Comment by kornelski** [comment] 2019-11-09 00:35
That's OK. Arithmetic doesn't have wide deployment, so that's not a big deal.

**Comment by dcommander** [comment] 2019-11-09 00:47
I concur.  The browsers that currently use libjpeg-turbo don't enable that feature.  The infrastructure is there to make fault-tolerant block smoothing work with arithmetic decoding.  Someone would just need to figure out how to detect an incomplete scan and set `entropy->pub.insufficient_data=TRUE` in **jdarith.c** whenever that occurs.
