### ISSUE TITLE
"Conditional jump or move depends on uninitialised value" if using jpeg12_write_scanlines() with samples > 4095

### ISSUE THREAD

**Issue by rouault** [libjpeg-turbo/libjpeg-turbo#633] opened 2022-11-25 16:10 UTC
**Clear and concise description of the bug:**

Not sure if it is a bug or intended, but if providing jpeg12_write_scanlines() with sample values > 4095, libjpeg-turbo raises warnings when run under Valgrind (I've also observed crashes). I know providing values > 4095 is non-sensical, that can happen if the user of the library doesn't validate inputs. If the absence of checks for that in the library is intended, probably that a warning should be added in libjpeg.txt  in the "12-bit Data Precision" paragraph. I'd note that I don't observe that issue when using libjpeg 6b built in 12-bit mode.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

A simple way of reproducing with cjpeg is to replace the rescale[] table of rdppmc.c with the identity
```
diff --git a/rdppm.c b/rdppm.c
index 0be36a6b..b560caa3 100644
--- a/rdppm.c
+++ b/rdppm.c
@@ -737,8 +737,7 @@ start_input_ppm(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
     half_maxval = maxval / 2;
     for (val = 0; val <= (long)maxval; val++) {
       /* The multiplication here must be done in 32 bits to avoid overflow */
-      source->rescale[val] = (_JSAMPLE)((val * _MAXJSAMPLE + half_maxval) /
-                                        maxval);
+      source->rescale[val] = (_JSAMPLE)val;
     }
   }
 }
```
and run ``valgrind ./cjpeg -precision 12 -outfile out.jpg in.ppm`` on the provide in.ppm which is a 8x8 3 channels uint16 ppm with values all set at 65535.

you'll get warnings like:
```
==2761145== Conditional jump or move depends on uninitialised value(s)
==2761145==    at 0x48D8B14: quantize (jcdctmgr.c:475)
==2761145==    by 0x48D8C6F: forward_DCT (jcdctmgr.c:528)
==2761145==    by 0x48D4F76: compress_first_pass (jccoefct.c:284)
==2761145==    by 0x48DAA3F: process_data_simple_main (jcmainct.c:103)
==2761145==    by 0x48D46AE: jpeg12_write_scanlines (jcapistd.c:119)
==2761145==    by 0x10BDF2: main (cjpeg.c:774)
==2761145== 
==2761145== Conditional jump or move depends on uninitialised value(s)
==2761145==    at 0x487A2F1: htest_one_block (jchuff.c:832)
==2761145==    by 0x487A560: encode_mcu_gather (jchuff.c:911)
==2761145==    by 0x48D530D: compress_output (jccoefct.c:383)
==2761145==    by 0x48D512D: compress_first_pass (jccoefct.c:328)
==2761145==    by 0x48DAA3F: process_data_simple_main (jcmainct.c:103)
==2761145==    by 0x48D46AE: jpeg12_write_scanlines (jcapistd.c:119)
==2761145==    by 0x10BDF2: main (cjpeg.c:774)
```

**Image(s) needed in order to reproduce the bug (if applicable):**

[in.ppm.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/10094085/in.ppm.zip)

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

ubuntu 20.04 x86_64

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

commit 8b9bc4b9635a2a047fb23ebe70c9acd728d3f99b (HEAD -> dev, origin/dev)

**Comment by dcommander** [comment] 2022-11-25 16:17
Probably a bug. I will investigate.

**Comment by dcommander** [comment] 2022-11-28 17:42
This appears to be a regression in the dev branch, since I cannot reproduce the issue with a 12-bit build of 2.0.x.

**Comment by dcommander** [comment] 2022-11-29 03:28
I was wrong.  With R/G/B values of 65535, I could only repro the issue with the dev branch, but with R/G/B values of 4096, I can repro the issue all the way back to jpeg-6b.
```
/*
 * This file was part of the Independent JPEG Group's software.
 * Copyright (C) 1992-1996, Thomas G. Lane.
 * libjpeg-turbo Modifications:
 * Copyright (C) 2017, 2019, 2022, D. R. Commander.
 * For conditions of distribution and use, see the accompanying README.ijg
 * file.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <jpeglib.h>
#include "jerror.h"
#include <setjmp.h>

#if LIBJPEG_TURBO_VERSION_NUMBER >= 2001080
typedef J12SAMPLE _JSAMPLE;
typedef J12SAMPROW _JSAMPROW;
typedef J12SAMPARRAY _JSAMPARRAY;
typedef J12SAMPIMAGE _JSAMPIMAGE;
#define _jpeg_write_scanlines jpeg12_write_scanlines
#else
#if BITS_IN_JSAMPLE != 12
#error BITS_IN_JSAMPLE must be 12
#endif
typedef JSAMPLE _JSAMPLE;
typedef JSAMPROW _JSAMPROW;
typedef JSAMPARRAY _JSAMPARRAY;
typedef JSAMPIMAGE _JSAMPIMAGE;
#define _jpeg_write_scanlines jpeg_write_scanlines
#endif


#define WIDTH  8
#define HEIGHT  8


METHODDEF(void)
write_JPEG_file(char *filename, int quality, int data_precision)
{
  struct jpeg_compress_struct cinfo;
  struct jpeg_error_mgr jerr;
  FILE *outfile;
  _JSAMPARRAY image_buffer = NULL;
  _JSAMPROW row_pointer[1];
  int row_stride, row, col;

  cinfo.err = jpeg_std_error(&jerr);
  jpeg_create_compress(&cinfo);

  if ((outfile = fopen(filename, "wb")) == NULL)
    ERREXIT(&cinfo, JERR_FILE_WRITE);
  jpeg_stdio_dest(&cinfo, outfile);

  cinfo.image_width = WIDTH;
  cinfo.image_height = HEIGHT;
  cinfo.input_components = 3;
  cinfo.in_color_space = JCS_RGB;
  cinfo.data_precision = data_precision;

  jpeg_set_defaults(&cinfo);
  jpeg_set_quality(&cinfo, quality, TRUE /* limit to baseline-JPEG values */);
  cinfo.comp_info[0].h_samp_factor = cinfo.comp_info[0].v_samp_factor = 1;

  jpeg_start_compress(&cinfo, TRUE);

  row_stride = WIDTH * 3;

  image_buffer = (_JSAMPARRAY)(*cinfo.mem->alloc_sarray)
    ((j_common_ptr)&cinfo, JPOOL_IMAGE, row_stride, HEIGHT);

  for (row = 0; row < HEIGHT; row++) {
    for (col = 0; col < WIDTH; col++) {
      image_buffer[row][col * 3] = 4096;
      image_buffer[row][col * 3 + 1] = 4096;
      image_buffer[row][col * 3 + 2] = 4096;
    }
  }

  while (cinfo.next_scanline < cinfo.image_height) {
    row_pointer[0] = image_buffer[cinfo.next_scanline];
    (void)_jpeg_write_scanlines(&cinfo, row_pointer, 1);
  }

  jpeg_finish_compress(&cinfo);
  fclose(outfile);

  jpeg_destroy_compress(&cinfo);
}


LOCAL(void)
usage(const char *progname)
{
  fprintf(stderr, "usage: %s outputfile[.jpg]\n", progname);

  exit(EXIT_FAILURE);
}


int
main(int argc, char **argv)
{
  int quality = 75;
  int data_precision = 12;

  if (sizeof(_JSAMPLE) != 2) {
    fprintf(stderr, "ERROR: Sample size is %lu bytes, not 2 bytes.\n",
            sizeof(_JSAMPLE));
    exit(1);
  }

  if (argc < 2)
    usage(argv[0]);

  write_JPEG_file(argv[1], quality, data_precision);

  return 0;
}
```

The root of the issue is that the input samples are overflowing the RGB-to-YCbCr conversion table.  I am trying to figure out an appropriate fix.

**Comment by dcommander** [comment] 2022-11-29 07:09
Should be fixed now

**Closed** 2022-11-29 07:09 UTC
Labels: bug
