### ISSUE TITLE
minor error in documentation

### ISSUE THREAD

**Issue by pdknsk** [libjpeg-turbo/libjpeg-turbo#86] opened 2016-06-18 07:59 UTC
```
int h_samp_factor
int v_samp_factor
        Horizontal and vertical sampling factors for the component; must
        be 1..4 according to the JPEG standard.  Note that larger sampling
        factors indicate a higher-resolution component; many people find
        this behavior quite unintuitive.  The default values are 2,2 for
        luminance components and 1,1 for chrominance components, except
        for grayscale where 1,1 is used.
```
In particular.

>  The default values are 2,2 for luminance components and 1,1 for chrominance components, [...].

Which is contradicted [elsewhere](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/libjpeg.txt#L1094) in the documentation.

        CAUTION: Setting separate quality levels for chrominance and luminance
        is mainly only useful if chrominance subsampling is disabled.  2x2
        chrominance subsampling (AKA "4:2:0") is the default, but you can
        explicitly disable subsampling as follows:

                cinfo->comp_info[0].v_samp_factor = 1;
                cinfo->comp_info[0].h_samp_factor = 1;

And in [code](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jcparam.c#L368).

```c
  case JCS_YCbCr:
    cinfo->write_JFIF_header = TRUE; /* Write a JFIF marker */
    cinfo->num_components = 3;
    /* JFIF specifies component IDs 1,2,3 */
    /* We default to 2x2 subsamples of chrominance */
    SET_COMP(0, 1, 2,2, 0, 0,0);
    SET_COMP(1, 2, 1,1, 1, 1,1);
    SET_COMP(2, 3, 1,1, 1, 1,1);
```

**Comment by dcommander** [comment] 2016-06-18 21:12
Please explain what is contradictory. I am not seeing it.

**Comment by pdknsk** [comment] 2016-06-19 07:56
In the quoted sentence, *luminance* and *chrominance* should be swapped.

**Comment by dcommander** [comment] 2016-06-19 12:16
Which sentence? You quoted several of them.

**Comment by pdknsk** [comment] 2016-06-19 12:22
>  The default values are 2,2 for luminance components and 1,1 for chrominance components, [...].

**Comment by dcommander** [comment] 2016-06-19 12:39
Which is explained in one of the other passages you quote. libjpeg and cjpeg have always specified subsampling factors backwards. 2x2 (4:2:0) chrominance subsampling is, for instance, selected by specifying horizontal and vertical subsampling factors of 2,2 for luminance and 1,1 for chrominance. 2,2 and 2x2 are not the same thing. In the libjpeg/cjpeg interface, what you are basically doing is telling the library how many of each component will be included in a pixel block. You're saying "for every 2 luminance components in the horizontal and vertical direction, include one chrominance component in the horizontal and vertical direction." This interface and its associated documentation have existed in libjpeg for decades. It was designed that way to allow for maximum flexibility, since it allows specifying any arbitrary subsampling factor on any component in any direction using only integers. The TurboJPEG API provides a less confusing but also less flexible interface. libjpeg-turbo emulates the libjpeg interfaces as closely as possible, so there is really nothing I can do to improve this.

**Closed by dcommander** 2016-06-19 12:39 UTC

**Comment by pdknsk** [comment] 2016-06-19 12:54
Thanks for the explanation. I withdraw my report. The documentation is right: it is *quite unintuitive*.
