### ISSUE TITLE
missing "stdio.h" header in jpeglib.h when building netpbm

### ISSUE THREAD

**Issue by david-geiger** [libjpeg-turbo/libjpeg-turbo#737] opened 2023-11-29 04:10 UTC
Hi,

When I tried to build netpbm (11.02.00) on Mageia Linux Cauldron I get the following build issue:

> In file included from camera.c:11:
/usr/include/jpeglib.h:916:52: error: unknown type name 'FILE'
  916 | EXTERN(void) jpeg_stdio_dest(j_compress_ptr cinfo, FILE *outfile);
      |                                                    ^~~~
/usr/include/jpeglib.h:32:1: note: 'FILE' is defined in header '<stdio.h>'; did you forget to '#include <stdio.h>'?

Shouldn't this header stdio.h be added in jpeglib.h?

Regards,
David

**Comment by dcommander** [comment] 2023-12-06 18:59
Duplicate of #17.  Please see my answer there.

**Closed by dcommander** 2023-12-06 18:59 UTC
Labels: bug
