### ISSUE TITLE
Unit tests fail when run on RISC-V

### ISSUE THREAD

**Issue by negge** [libjpeg-turbo/libjpeg-turbo#710] opened 2023-07-24 19:35 UTC
I tried to build and run the libjpeg-turbo (git hash e429e37) tests on emulated RISCV via qemu-system-riscv64 and got 2 failed tests out of 590.

```
nathan@gentoo-riscv ~/git/libjpeg-turbo/build $ make test
Running tests...
Test project /home/nathan/git/libjpeg-turbo/build
        Start   1: tjunittest-shared
  1/590 Test   #1: tjunittest-shared ...................................   Passed   81.90 sec
        Start   2: tjunittest-shared-alloc
  2/590 Test   #2: tjunittest-shared-alloc .............................   Passed   81.50 sec
        Start   3: tjunittest-shared-yuv
  3/590 Test   #3: tjunittest-shared-yuv ...............................   Passed   50.12 sec
        Start   4: tjunittest-shared-yuv-alloc
  4/590 Test   #4: tjunittest-shared-yuv-alloc .........................   Passed   44.47 sec
        Start   5: tjunittest-shared-yuv-nopad
  5/590 Test   #5: tjunittest-shared-yuv-nopad .........................   Passed   46.65 sec
        Start   6: tjunittest-shared-lossless
...
130/590 Test #130: cjpeg-shared-420s-ifast-opt .........................   Passed    0.11 sec
        Start 131: cjpeg-shared-420s-ifast-opt-cmp
131/590 Test #131: cjpeg-shared-420s-ifast-opt-cmp .....................   Passed    0.05 sec
        Start 132: cjpeg-shared-3x2-float-prog
132/590 Test #132: cjpeg-shared-3x2-float-prog .........................   Passed    0.08 sec
        Start 133: cjpeg-shared-3x2-float-prog-cmp
133/590 Test #133: cjpeg-shared-3x2-float-prog-cmp .....................   Passed    0.04 sec
        Start 134: djpeg-shared-3x2-float-prog
134/590 Test #134: djpeg-shared-3x2-float-prog .........................   Passed    0.07 sec
        Start 135: djpeg-shared-3x2-float-prog-cmp
135/590 Test #135: djpeg-shared-3x2-float-prog-cmp .....................***Failed    0.04 sec
        Start 136: cjpeg-shared-3x2-ifast-prog
136/590 Test #136: cjpeg-shared-3x2-ifast-prog .........................   Passed    0.07 sec
        Start 137: cjpeg-shared-3x2-ifast-prog-cmp
137/590 Test #137: cjpeg-shared-3x2-ifast-prog-cmp .....................   Passed    0.04 sec
        Start 138: djpeg-shared-3x2-ifast-prog
138/590 Test #138: djpeg-shared-3x2-ifast-prog .........................   Passed    0.07 sec
        Start 139: djpeg-shared-3x2-ifast-prog-cmp
139/590 Test #139: djpeg-shared-3x2-ifast-prog-cmp .....................   Passed    0.04 sec
        Start 140: cjpeg-shared-420-islow-ari
140/590 Test #140: cjpeg-shared-420-islow-ari ..........................   Passed    0.06 sec
        Start 141: cjpeg-shared-420-islow-ari-cmp
...
425/590 Test #425: cjpeg-static-420s-ifast-opt .........................   Passed    0.07 sec
        Start 426: cjpeg-static-420s-ifast-opt-cmp
426/590 Test #426: cjpeg-static-420s-ifast-opt-cmp .....................   Passed    0.04 sec
        Start 427: cjpeg-static-3x2-float-prog
427/590 Test #427: cjpeg-static-3x2-float-prog .........................   Passed    0.08 sec
        Start 428: cjpeg-static-3x2-float-prog-cmp
428/590 Test #428: cjpeg-static-3x2-float-prog-cmp .....................   Passed    0.04 sec
        Start 429: djpeg-static-3x2-float-prog
429/590 Test #429: djpeg-static-3x2-float-prog .........................   Passed    0.07 sec
        Start 430: djpeg-static-3x2-float-prog-cmp
430/590 Test #430: djpeg-static-3x2-float-prog-cmp .....................***Failed    0.04 sec
        Start 431: cjpeg-static-3x2-ifast-prog
431/590 Test #431: cjpeg-static-3x2-ifast-prog .........................   Passed    0.07 sec
        Start 432: cjpeg-static-3x2-ifast-prog-cmp
432/590 Test #432: cjpeg-static-3x2-ifast-prog-cmp .....................   Passed    0.04 sec
        Start 433: djpeg-static-3x2-ifast-prog
433/590 Test #433: djpeg-static-3x2-ifast-prog .........................   Passed    0.08 sec
        Start 434: djpeg-static-3x2-ifast-prog-cmp
434/590 Test #434: djpeg-static-3x2-ifast-prog-cmp .....................   Passed    0.04 sec
        Start 435: cjpeg-static-420-islow-ari
435/590 Test #435: cjpeg-static-420-islow-ari ..........................   Passed    0.07 sec
        Start 436: cjpeg-static-420-islow-ari-cmp
436/590 Test #436: cjpeg-static-420-islow-ari-cmp ......................   Passed    0.04 sec
        Start 437: jpegtran-static-420-islow-ari
437/590 Test #437: jpegtran-static-420-islow-ari .......................   Passed    0.06 sec
        Start 438: jpegtran-static-420-islow-ari-cmp
438/590 Test #438: jpegtran-static-420-islow-ari-cmp ...................   Passed    0.05 sec
        Start 439: cjpeg-static-444-islow-progari
439/590 Test #439: cjpeg-static-444-islow-progari ......................   Passed    0.08 sec
        Start 440: cjpeg-static-444-islow-progari-cmp
440/590 Test #440: cjpeg-static-444-islow-progari-cmp ..................   Passed    0.04 sec
        Start 441: djpeg-static-420m-ifast-ari
...
570/590 Test #570: cjpeg12-static-lossless .............................   Passed    0.08 sec
        Start 571: cjpeg12-static-lossless-cmp
571/590 Test #571: cjpeg12-static-lossless-cmp .........................   Passed    0.04 sec
        Start 572: djpeg12-static-lossless
572/590 Test #572: djpeg12-static-lossless .............................   Passed    0.07 sec
        Start 573: djpeg12-static-lossless-cmp
573/590 Test #573: djpeg12-static-lossless-cmp .........................   Passed    0.04 sec
        Start 574: djpeg12-static-420-islow-skip15_31
574/590 Test #574: djpeg12-static-420-islow-skip15_31 ..................   Passed    0.07 sec
        Start 575: djpeg12-static-420-islow-skip15_31-cmp
575/590 Test #575: djpeg12-static-420-islow-skip15_31-cmp ..............   Passed    0.04 sec
        Start 576: cjpeg12-static-420-islow-prog
576/590 Test #576: cjpeg12-static-420-islow-prog .......................   Passed    0.08 sec
        Start 577: djpeg12-static-420-islow-prog-crop62x62_71_71
577/590 Test #577: djpeg12-static-420-islow-prog-crop62x62_71_71 .......   Passed    0.09 sec
        Start 578: djpeg12-static-420-islow-prog-crop62x62_71_71-cmp
578/590 Test #578: djpeg12-static-420-islow-prog-crop62x62_71_71-cmp ...   Passed    0.05 sec
        Start 579: cjpeg12-static-444-islow
579/590 Test #579: cjpeg12-static-444-islow ............................   Passed    0.08 sec
        Start 580: djpeg12-static-444-islow-skip1_6
580/590 Test #580: djpeg12-static-444-islow-skip1_6 ....................   Passed    0.07 sec
        Start 581: djpeg12-static-444-islow-skip1_6-cmp
581/590 Test #581: djpeg12-static-444-islow-skip1_6-cmp ................   Passed    0.04 sec
        Start 582: cjpeg12-static-444-islow-prog
582/590 Test #582: cjpeg12-static-444-islow-prog .......................   Passed    0.09 sec
        Start 583: djpeg12-static-444-islow-prog-crop98x98_13_13
583/590 Test #583: djpeg12-static-444-islow-prog-crop98x98_13_13 .......   Passed    0.07 sec
        Start 584: djpeg12-static-444-islow-prog-crop98x98_13_13-cmp
584/590 Test #584: djpeg12-static-444-islow-prog-crop98x98_13_13-cmp ...   Passed    0.04 sec
        Start 585: jpegtran12-static-crop
585/590 Test #585: jpegtran12-static-crop ..............................   Passed    0.06 sec
        Start 586: jpegtran12-static-crop-cmp
586/590 Test #586: jpegtran12-static-crop-cmp ..........................   Passed    0.04 sec
        Start 587: example-12bit-static-compress
587/590 Test #587: example-12bit-static-compress .......................   Passed    0.15 sec
        Start 588: example-12bit-static-compress-cmp
588/590 Test #588: example-12bit-static-compress-cmp ...................   Passed    0.04 sec
        Start 589: example-12bit-static-decompress
589/590 Test #589: example-12bit-static-decompress .....................   Passed    0.16 sec
        Start 590: example-12bit-static-decompress-cmp
590/590 Test #590: example-12bit-static-decompress-cmp .................   Passed    0.06 sec

99% tests passed, 2 tests failed out of 590

Total Test time (real) = 1151.41 sec

The following tests FAILED:
	135 - djpeg-shared-3x2-float-prog-cmp (Failed)
	430 - djpeg-static-3x2-float-prog-cmp (Failed)
Errors while running CTest
Output from these tests are in: /home/nathan/git/libjpeg-turbo/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```

**Comment by dcommander** [comment] 2023-07-24 20:16
Duplicate of #709

**Comment by negge** [comment] 2023-07-24 20:28
Tests pass on x86_64.

**Comment by dcommander** [comment] 2023-07-25 14:14
I just noticed that these failures are in the 8-bit floating point DCT/IDCT tests rather than in the 12-bit tests.  Thus, this is actually a slightly different issue than #709.  Please post the output with `--output-on-failure` passed to ctest.  That will help me determine the exact cause of the failure.  I also need to know:
- whether the same failure occurs with libjpeg-turbo 2.1.x
- the exact compiler and version you are using

**Comment by dcommander** [comment] 2023-07-25 17:40
The build no longer sets `FLOATTEST8` by default for non-x86 builds, so this issue should now be worked around.  However, I would still be curious to know the actual MD5 sums that the tests are generating on your system and which compiler you are using.

**Closed by dcommander** 2023-07-25 17:40 UTC

**Comment by Xeonacid** [comment] 2023-09-07 11:19
> The build system no longer sets `FLOATTEST8` by default for non-x86 builds, so this issue should now be worked around. However, I would still be curious to know the actual MD5 sums that the tests are generating on your system and which compiler you are using.

FYI I'm using the below GCC on Arch Linux RISC-V with the following MD5 sum:

```text
xeonacid@centiskorch ~> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/riscv64-unknown-linux-gnu/13.2.1/lto-wrapper
Target: riscv64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,d,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-multilib --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.1 20230801 (GCC)
```
```text
205/306 Test #146: djpeg-shared-3x2-float-prog-cmp .....................***Failed    0.15 sec
testout_3x2_float.ppm: FAILED.  Checksum is 0e917a34193ef976b679a6b069b1be26
```

**Comment by dcommander** [comment] 2023-09-11 16:16
That means that the correct setting for `FLOATTEST8` (and probably `FLOATTEST12` as well) is `fp-contract`.
