### ISSUE TITLE
For Java: provide this library as a single cross-platform Jar

### ISSUE THREAD

**Issue by farrellf** [libjpeg-turbo/libjpeg-turbo#415] opened 2020-03-01 18:36 UTC
I'd like to provide my program as a single cross-platform fat Jar. If I understand things correctly, that is not possible with libjpeg-turbo.

It seems like I must pick a libjpeg-turbo Jar for a specific platform, which means my resulting fat Jar would be tied to that one platform. And I can't simply include multiple libjpeg-turbo Jars on the classpath, because they all implement the same classes. Or am I misunderstanding something?

**Comment by dcommander** [comment] 2020-03-02 18:09
libjpeg-turbo is fundamentally a C library that includes run-time-selectable hand-tuned assembly functions that accelerate specific C library functions on specific platforms.  Thus, the TurboJPEG Java API is a wrapper.  It relies on JNI in order to access the underlying C library.  If there is a way to include the most common libjpeg-turbo architectures into a single JAR, I would be open to that, if:
1. You or someone else can provide details on the structure of multi-architecture fat JARs and how I could create them (I wasn't able to find those details after a cursory Google search.)
2. The construction of a fat JAR can be done within the confines of our official build system, which generally executes different platform builds sequentially.

**Comment by dcommander** [comment] 2020-03-02 18:28
Note that the current JAR deployment scheme in libjpeg-turbo was designed to support Java Web Start, which expects a separate JAR for every different JNI architecture.  However, Java Web Start is an obsolete technology, so I'm open to supporting a more modern use case if there is one.

**Comment by farrellf** [comment] 2020-03-03 16:59
I don't personally have experience with packaging up libraries, but it might be helpful to look at how "jSerialComm" does things. jSerialComm is an open-source Java library that uses JNI, supports several platforms and architectures, and is packaged as a single Jar file.

It looks like their build process is documented here:
https://github.com/Fazecast/jSerialComm

**Comment by dcommander** [comment] 2020-06-16 16:49
It seems straightforward enough, but unfortunately it's not a good fit for our build/packaging system, which builds binaries for various platforms asynchronously and thus can't currently accommodate cross-platform dependencies.  I could write a Bash script that runs as part of the deployment process for official releases, so it could build a fat JAR from all of the binary packages once they are built.  However, there would be no way to do that except in the official builds, which are performed in a single shared directory.  Thus, a fat JAR couldn't be built as part of the continuous integration process.  Best practices dictate that, if we're going to provide a binary package to support a particular use case, we need to provide that binary package both via continuous integration as well as the official release process.  That ensures that the binary package receives continuous testing.

At the moment, I think it makes the most sense for a fat JAR to be maintained by someone else, particularly if it is intended to be deployed to Maven or another distribution channel that we don't officially support.  My own downstream project that uses the libjpeg-turbo JAR files (TurboVNC) doesn't need a fat JAR, so I couldn't eat my own dog food on this, and I'm not convinced that the demand for a fat libjpeg-turbo JAR is sufficient to justify the expense of officially supporting one.

I would be willing to spend time on this if there were a reasonable way to support a fat JAR in our continuous integration builds.  Otherwise, however, my concern is the inability to test such a fat JAR in any official capacity.  The existing JAR files are tested as part of the build process, so there would need to be a way for us to test the fat JAR as well.  I can't think of any reasonably robust way to do that with our existing build/packaging system.

If someone else wants to develop a script for generating a fat JAR from an existing libjpeg-turbo release, I will consider adding that script to another repository within the libjpeg-turbo GitHub organization.  I won't, however, consider deploying the fat JAR into our official binary distribution unless there is a way to automatically test the fat JAR on all platforms it claims to support.

**Comment by dcommander** [comment] 2020-06-16 16:50
Closing as "won't implement" for now, but I will reconsider if new information comes to light.

**Closed by dcommander** 2020-06-16 16:49 UTC
Labels: enhancement
