### ISSUE TITLE
Arm Neon: Autodetection of vld1_s16_x3(), vld1_u16_x2(), and vld1q_u8_x4() intrinsics fails under GCC 10-11

### ISSUE THREAD

**Issue by dcommander** [libjpeg-turbo/libjpeg-turbo#547] opened 2021-08-26 20:58 UTC
Not sure whether this is a libjpeg-turbo bug or a GCC bug.  When testing under Ubuntu 20.04 and 21.04, I observe that Clang 9 through Clang 12 properly detect the aforementioned Neon intrinsics and thus enable `NEON_INTRINSICS` by default.  With GCC 9 and earlier, the intrinsics are not detected in **arm_neon.h**, so `NEON_INTRINSICS` is disabled by default.  That is expected.  However, with GCC 10 and GCC 11, the intrinsics are detected in **arm_neon.h**, but the test program cannot subsequently be linked:
```
Determining if the vld1_s16_x3 exist failed with the following output:
Change Dir: /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_1e31b/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_1e31b.dir/build.make CMakeFiles/cmTC_1e31b.dir/build
gmake[1]: Entering directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1e31b.dir/CheckSymbolExists.c.o
/usr/bin/aarch64-linux-gnu-gcc-11   -Wall -Werror  -o CMakeFiles/cmTC_1e31b.dir/CheckSymbolExists.c.o -c /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_1e31b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1e31b.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc-11 -Wall -Werror  -rdynamic CMakeFiles/cmTC_1e31b.dir/CheckSymbolExists.c.o -o cmTC_1e31b 
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CMakeFiles/cmTC_1e31b.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `vld1_s16_x3'
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CheckSymbolExists.c:(.text+0x18): undefined reference to `vld1_s16_x3'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_1e31b.dir/build.make:106: cmTC_1e31b] Error 1
gmake[1]: Leaving directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_1e31b/fast] Error 2


File /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <arm_neon.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef vld1_s16_x3
  return ((int*)(&vld1_s16_x3))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the vld1_u16_x2 exist failed with the following output:
Change Dir: /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_0d0c0/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_0d0c0.dir/build.make CMakeFiles/cmTC_0d0c0.dir/build
gmake[1]: Entering directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0d0c0.dir/CheckSymbolExists.c.o
/usr/bin/aarch64-linux-gnu-gcc-11   -Wall -Werror  -o CMakeFiles/cmTC_0d0c0.dir/CheckSymbolExists.c.o -c /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_0d0c0
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0d0c0.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc-11 -Wall -Werror  -rdynamic CMakeFiles/cmTC_0d0c0.dir/CheckSymbolExists.c.o -o cmTC_0d0c0 
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CMakeFiles/cmTC_0d0c0.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `vld1_u16_x2'
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CheckSymbolExists.c:(.text+0x18): undefined reference to `vld1_u16_x2'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_0d0c0.dir/build.make:106: cmTC_0d0c0] Error 1
gmake[1]: Leaving directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_0d0c0/fast] Error 2


File /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <arm_neon.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef vld1_u16_x2
  return ((int*)(&vld1_u16_x2))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the vld1q_u8_x4 exist failed with the following output:
Change Dir: /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_f440f/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_f440f.dir/build.make CMakeFiles/cmTC_f440f.dir/build
gmake[1]: Entering directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f440f.dir/CheckSymbolExists.c.o
/usr/bin/aarch64-linux-gnu-gcc-11   -Wall -Werror  -o CMakeFiles/cmTC_f440f.dir/CheckSymbolExists.c.o -c /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_f440f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f440f.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc-11 -Wall -Werror  -rdynamic CMakeFiles/cmTC_f440f.dir/CheckSymbolExists.c.o -o cmTC_f440f 
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CMakeFiles/cmTC_f440f.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `vld1q_u8_x4'
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: CheckSymbolExists.c:(.text+0x18): undefined reference to `vld1q_u8_x4'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_f440f.dir/build.make:106: cmTC_f440f] Error 1
gmake[1]: Leaving directory '/home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_f440f/fast] Error 2


File /home/drc/src/libjpeg-turbo/linux64.arm/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <arm_neon.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef vld1q_u8_x4
  return ((int*)(&vld1q_u8_x4))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by dcommander** [comment] 2021-10-02 00:03
@jwright-arm I figured out how to properly autodetect the intrinsics in question when using GCC 10-11, using the patch below:

```
--- a/simd/CMakeLists.txt
+++ b/simd/CMakeLists.txt
@@ -241,13 +241,65 @@ if(BITS EQUAL 32)
   endif()
 endif()

-include(CheckSymbolExists)
 if(BITS EQUAL 32)
   set(CMAKE_REQUIRED_FLAGS "-mfpu=neon ${SOFTFP_FLAG}")
 endif()
-check_symbol_exists(vld1_s16_x3 arm_neon.h HAVE_VLD1_S16_X3)
-check_symbol_exists(vld1_u16_x2 arm_neon.h HAVE_VLD1_U16_X2)
-check_symbol_exists(vld1q_u8_x4 arm_neon.h HAVE_VLD1Q_U8_X4)
+check_c_source_compiles("
+  #include <arm_neon.h>
+  int main(int argc, char **argv) {
+    const int16_t input[] = {
+      (int16_t)argc, (int16_t)argc, (int16_t)argc, (int16_t)argc,
+      (int16_t)argc, (int16_t)argc, (int16_t)argc, (int16_t)argc,
+      (int16_t)argc, (int16_t)argc, (int16_t)argc, (int16_t)argc
+    };
+    int16x4x3_t output = vld1_s16_x3(input);
+    return (int)output.val[0][0];
+  }" HAVE_VLD1_S16_X3)
+check_c_source_compiles("
+  #include <arm_neon.h>
+  int main(int argc, char **argv) {
+    const uint16_t input[] = {
+      (uint16_t)argc, (uint16_t)argc, (uint16_t)argc, (uint16_t)argc,
+      (uint16_t)argc, (uint16_t)argc, (uint16_t)argc, (uint16_t)argc
+    };
+    uint16x4x2_t output = vld1_u16_x2(input);
+    return (int)output.val[0][0];
+  }" HAVE_VLD1_U16_X2)
+check_c_source_compiles("
+  #include <arm_neon.h>
+  int main(int argc, char **argv) {
+    const uint8_t input[] = {
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc,
+      (uint8_t)argc, (uint8_t)argc, (uint8_t)argc, (uint8_t)argc
+    };
+    uint8x16x4_t output = vld1q_u8_x4(input);
+    return (int)output.val[0][0];
+  }" HAVE_VLD1Q_U8_X4)
 if(BITS EQUAL 32)
   unset(CMAKE_REQUIRED_FLAGS)
 endif()
```

However, unfortunately the net result of this is a serious performance regression with both GCC 10 and 11 (albeit less serious with GCC 11-- 2-10% vs. 10-15% on average.)  For all intents and purposes, autodetection of `vld1_s16_x3()`, `vld1_u16_x2()`, and `vld1q_u8_x4()` is an ineffective proxy for optimal Neon intrinsics support when using GCC.

I would really appreciate Arm's input on this, since our project budget for this year is completely exhausted.

**Comment by jwright-arm** [comment] 2021-10-04 15:02
It'll be a couple of days but I'll take a look at this to see what's going on here. (I'm not surprised by the performance coming out of GCC 10, but I am a little surprised by that of GCC 11.) I suppose in the worst case we just keep using the Neon assembly paths for all GCC versions, with the option of a manual override as exists currently.

Could you let me know the details of your setup so that I can attempt to reproduce these numbers:
- CPU/SoC of your test platform
- Core/frequency pinning details (if any)
- Exact `tjbench` command line (so I know what DCT, sampling and color conversion paths I should be looking at)
- Image corpus

Also, are the regression numbers quoted for encode, decode or both?

**Comment by dcommander** [comment] 2021-10-04 17:15
The results I quoted above were from an in-order core (Cortex-A53.)  The slowdown is generally less severe with an out-of-order core (Cortex-A72.)  I built libjpeg-turbo using the GCC 10 and 11 AArch64 cross-compilers under Ubuntu 20.04 and 21.04, respectively.  The test images are the [same ones I used](https://libjpeg-turbo.org/About/Performance) when evaluating the Neon SIMD overhaul in libjpeg-turbo 2.1.  [This spreadsheet](https://github.com/libjpeg-turbo/libjpeg-turbo/files/7279923/libjpegturbo-armintrinsics-gcc10-11.ods) has all of the CPU info and results.  Generally the Rock960 gives me about +/- 2% accuracy unless I take additional (time-consuming) measures to improve the accuracy.  I took those measures when evaluating the Neon SIMD overhaul in libjpeg-turbo 2.1, but I did not do so here.

Note also that, with GCC 11, the GAS performance prior to 129f0cb76346ceede8f4d8d87dea8acb0809056c was abysmal, so I tested the tip of the main branch.

The ideal situation for libjpeg-turbo would be that the build system auto-enables `NEON_INTRINSICS` for compilers that have fully-performant implementations of Neon intrinsics ("fully performant" = no more than 5% regression for all tests, relative to GAS.)  If that means GCC 12 and later, then perhaps the build system should just specifically set `NEON_INTRINSICS=0` by default for GCC 10-11.  Note that GCC 11 is fully performant for decompression but not for compression.

**Comment by jwright-arm** [comment] 2021-11-25 17:48
Apologies for the delay here - the rush to get stuff merged before the GCC 12 stage 1 cut off meant this got put on hold.

I don't know what to say about the in-order core performance you're seeing with GCC 11 - I can't reproduce it. That said, the slowdown on the out of order core is reproducible, and pushes up against the 5% regression limit. [Here](https://github.com/libjpeg-turbo/libjpeg-turbo/files/7604615/libjpegturbo-armintrinsics-gcc11-12.ods) are my GCC 11 benchmark results on an out-of-order Neoverse-N1 core.

I've also done benchmarking with a build of the current GCC tree - a semi-reasonable approximation for GCC 12 now stage 1 development is finished. Note the significant bump in baseline performance over GCC 11 - mostly due to accelerating the Neon intrinsics code present in the `NEON_INTRINSICS=0` build. The performance of the `NEON_INTRINSICS=1` build surpasses that of the GAS build now too.

I suppose the TL;DR here is: set `NEON_INTRINSICS=1` for GCC versions >=12, and keep the GAS implementation for older GCC versions.

**Comment by dcommander** [comment] 2021-11-25 19:59
Do the automated checks in the libjpeg-turbo build system still fail under GCC 12?

**Comment by jwright-arm** [comment] 2021-11-25 20:54
Without your changes here[1], yes.

[1] https://github.com/libjpeg-turbo/libjpeg-turbo/issues/547#issuecomment-932640497

**Comment by dcommander** [comment] 2021-11-25 23:29
I don’t see much point in keeping the automatic intrinsics checks, then. If enabling full intrinsics by default is still something that requires knowledge of the compiler version histories in order to get right, then we shouldn’t pretend otherwise.

I will look into it again next week.

**Comment by jwright-arm** [comment] 2021-11-26 15:07
The checks here[1] are still necessary because older GCC versions (<10) don't support the intrinsics at all. E.g. if someone tried to compile with GCC 9 and manually specified `NEON_INTRINSICS=1`, the build would fail if the `HAVE_VLD1_S16_X3`, etc macros weren't set appropriately.

I think we want to change:
```
if((HAVE_VLD1_S16_X3 AND HAVE_VLD1_U16_X2 AND HAVE_VLD1Q_U8_X4) OR APPLE)
  set(DEFAULT_NEON_INTRINSICS 1)
else()
  set(DEFAULT_NEON_INTRINSICS 0)
endif()
```
To something like:
```
if((CMAKE_COMPILER_IS_GNUCC AND CMAKE_C_COMPILER_VERSION VERSION_LESS 12.0.0)
   OR (BITS EQUAL 32 AND NOT (HAVE_VLD1_S16_X3 AND HAVE_VLD1_U16_X2 AND HAVE_VLD1Q_U8_X4)))
  set(DEFAULT_NEON_INTRINSICS 0)
else()
  set(DEFAULT_NEON_INTRINSICS 1)
endif()
```

[1] https://github.com/libjpeg-turbo/libjpeg-turbo/issues/547#issuecomment-932640497

**Comment by dcommander** [comment] 2021-12-01 16:57
The modified intrinsics checks always fail with GCC 10 and 11 when building for AArch32.  Can you confirm that they succeed with GCC 12/AArch32?

**Comment by jwright-arm** [comment] 2021-12-01 17:06
Sadly not, these still haven't been implemented for GCC's AArch32 backend.

**Comment by dcommander** [comment] 2021-12-01 17:11
OK, so you would recommend that we continue to use GAS for AArch32 when using GCC 12?

**Closed** 2021-12-01 17:33 UTC
Labels: bug

**Comment by jwright-arm** [comment] 2021-12-01 17:39
I'd need to check the performance to see what's what for AArch32 using GCC - for now I'd suggest keeping things the way they are.

**Comment by dcommander** [comment] 2021-12-02 01:20
The changes have been implemented.  I have tested Clang 3.9-12 and GCC 4-11 and verified that the three intrinsics are all detected with Clang/AArch64, Clang/AArch32 7-12, and GCC/AArch64 10-11, and some of them are detected with GCC/AArch64 8-9.  The build system now automatically enables the full Neon intrinsics SIMD implementation based on the following rules:
- If all three intrinsics are present and the compiler is not GCC 10-11, then enable the full Neon intrinsics SIMD implementation by default (but allow the user to override that decision.)
- If some of the three intrinsics are not present but GAS is broken (i.e. it would require gas-preprocessor.pl), then force-enable the full Neon intrinsics SIMD implementation.  (This affects some older Clang releases.)

I cannot test GCC 12, so please verify the expected behavior:
- With GCC 12/AArch64, all three intrinsics should be detected, and the build system should enable the intrinsics implementation by default.
- With GCC 12/AArch32, all three intrinsics should not be detected, and the build system should disable the intrinsics implementation by default.

**Comment by jwright-arm** [comment] 2021-12-02 15:20
Looks good - the observed behavior with GCC 12 lines up with what is expected for both AArch32 and AArch64.

**Comment by dcommander** [comment] 2022-01-05 22:48
I have since discovered that Linaro provides [GCC 12 builds that work with RHEL 8](https://snapshots.linaro.org/gnu-toolchain/), so I am now able to test GCC 12.

**Comment by dcommander** [comment] 2022-02-11 00:31
@jwright-arm Unfortunately this fix broke Visual Studio/AArch64 builds.  Can you confirm?  Perhaps we should just bypass the intrinsics checks for MSVC, because the only way to build libjpeg-turbo/AArch64 with MSVC is to use full intrinsics.

**Comment by dcommander** [comment] 2022-02-11 04:32
Never mind.  I figured it out.
