### ISSUE TITLE
Artifacts when doing DCT downscaling

### ISSUE THREAD

**Issue by andrescj-chromium** [libjpeg-turbo/libjpeg-turbo#297] opened 2018-10-10 22:55 UTC
Hi,

We're having some problems when requesting a downscaled decode. The image in question is attached to https://bugs.chromium.org/p/chromium/issues/detail?id=890745.

This particular image has a 4:4:4 subsampling and it cannot fit a whole number of 8x8 MCUs vertically. So, it looks like the encoder decided to use some "bogus" data to create the last row of MCUs (see comment 10 in that bug for an extended explanation).

For now, we have decided to mitigate this by only requesting a downscaled decode if the original dimensions can accommodate a whole number of MCUs in both directions. However, is this something that can be "fixed" at the libjpeg-turbo level such that these artifacts are not seen? I'm not really sure to what extent this can be considered a bug.

Thanks!

**Comment by dcommander** [comment] 2018-10-11 15:17
If you can identify this as a regression in a particular version of libjpeg-turbo, or as a regression relative to libjpeg v6b, then I would consider that a bug in our code, but as far as I can determine, libjpeg-turbo behaves [as advertised](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/README.md#mathematical-compatibility) on this image-- producing identical results to jpeg-8 and jpeg-9 if scaling factors other than 1/4 and 1/2 are used, and producing identical results to jpeg-6b if scaling factors of 1/2 or 1/4 are used.  Thus, the behavior appears to me to be canonical and not a bug.

**Comment by dcommander** [comment] 2018-10-13 14:01
I would also entertain code that addresses this issue in libjpeg-turbo, although I would need to have a better understanding of the issue before integrating said code.  At the moment, I'm still not convinced that libjpeg-turbo is doing anything wrong.  Closing this until/unless further information comes to light.

**Closed by dcommander** 2018-10-13 14:01 UTC

**Comment by nico** [comment] 2026-07-08 20:15
Here's my attempt at writing up motivation, what's happening, and what could possibly changed. (Hand-written, fwiw.)

I think the main use case for scale_denom is to load lower-resolution versions of jpegs more quickly. For example, if a PDF or HTML file (or whatever) contains a 1024x1024 jpeg image, but it's only drawn at 128x128 pixels on screen, the PDF viewer (etc) could set scale_denom to 8. This will save doing full IDCTs (just need to return the DC component for each tile), and it also doesn't require a 1024x1024 -> 128x128 downsample at paint time. Both save space and time.

However, if a JPEG's dimensions aren't a multiple of the MCU size, then the DCT tiles on the right and bottom edges of the image contain a DC component that is computed over both the in-image parts of the tile as well as the invisible padding pixels of the tile. If an encoder for example writes black pixels in these invisible padding pixels, the DC component will have black mixed into it, and setting scale_denom to 8 will produce an image that has a black border, like in the original report.

(The encoder could repeat the in-tile pixels into the padding to prevent this. But PDFs and HTML files contain JPEGs from all kinds of encoders, so viewers can't assume that JPEGs are in any way well-behaved.)

I can't come up with a good way to make this work for images whose dimensions aren't a multiple of the MCU size with the current API. Chrome for example only sets scale_denum for MCU-multiple images, and so does pdfium after https://pdfium-review.googlesource.com/c/pdfium/+/151550.

One idea would be to ignore pixels from partial tiles, but this cuts off borders around images (if the border is part of the image), which is pretty visible and won't work.

Another idea would be to decode the rightmost and bottommost two tiles at full resolution when scale_denom is set, and computing the DC component (for scale_denom 8, and more values for 2 and 4) from the rightmost / bottommost full 8x8 tile. This would keep border pixels, it shouldn't produce discontinuities, and it should work fairly well. (…unless someone comes up with a case I haven't thought of.) As far as I can tell, it's not possible to implement this form outside of libjpeg-turbo, as scale_denom is an image-global setting. (And doing two decode passes sacrifices all time and memory benefits of using scale_denom in the first place.)

Maybe libjpeg-turbo could grow a `scale_denom_border_resampling` bool setting to opt in to this behavior, and it setting some macro in a header (`JPEG_LIB_HAVE_SCALE_DENOM_BORDER_RESAMPLING` or what) that client code could check for to see if it that config toggle exists. (This would prevent every user of libjpeg-turbo having to autoconf for it.) If it's set, libjpeg-turbo would do the full-decode for the two right/bottom-most tiles and resampling as described above.

With this, viewers could use scale_denom for all JPEG images.

Would a PR around these lines have chances of being accepted?

**Comment by dcommander** [comment] 2026-07-08 22:27
> I think the main use case for scale_denom is to load lower-resolution versions of jpegs more quickly. For example, if a PDF or HTML file (or whatever) contains a 1024x1024 jpeg image, but it's only drawn at 128x128 pixels on screen, the PDF viewer (etc) could set scale_denom to 8. This will save doing full IDCTs (just need to return the DC component for each tile), and it also doesn't require a 1024x1024 -> 128x128 downsample at paint time. Both save space and time.

"More quickly" was a valid assumption 35 years ago (when libjpeg was created) but is not necessarily valid today. Only the 1/2 and 1/4 scaled IDCTs are SIMD-accelerated, so for other scaling factors, it may be quicker to decompress the whole image and perform image space scaling, particularly if the image space scaling algorithm is SIMD accelerated. The scaled IDCTs save memory, but that isn't as big of a concern as it was 35 years ago. Most of the interest in IDCT scaling these days seems to come from embedded developers. Desktops are fast enough that users will hardly notice any speed advantage to IDCT scaling vs. image space scaling, even in cases where there is an advantage. Mostly the feature exists for backward compatibility with libjpeg, and this complaint would apply just as readily to libjpeg.

> However, if a JPEG's dimensions aren't a multiple of the MCU size, then the DCT tiles on the right and bottom edges of the image contain a DC component that is computed over both the in-image parts of the tile as well as the invisible padding pixels of the tile. If an encoder for example writes black pixels in these invisible padding pixels, the DC component will have black mixed into it, and setting scale_denom to 8 will produce an image that has a black border, like in the original report.
> 
> (The encoder could repeat the in-tile pixels into the padding to prevent this. But PDFs and HTML files contain JPEGs from all kinds of encoders, so viewers can't assume that JPEGs are in any way well-behaved.)
> 
> I can't come up with a good way to make this work for images whose dimensions aren't a multiple of the MCU size with the current API. Chrome for example only sets scale_denum for MCU-multiple images, and so does pdfium after https://pdfium-review.googlesource.com/c/pdfium/+/151550.
> 
> One idea would be to ignore pixels from partial tiles, but this cuts off borders around images (if the border is part of the image), which is pretty visible and won't work.
> 
> Another idea would be to decode the rightmost and bottommost two tiles at full resolution when scale_denom is set, and computing the DC component (for scale_denom 8, and more values for 2 and 4) from the rightmost / bottommost full 8x8 tile. This would keep border pixels, it shouldn't produce discontinuities, and it should work fairly well. (…unless someone comes up with a case I haven't thought of.) As far as I can tell, it's not possible to implement this form outside of libjpeg-turbo, as scale_denom is an image-global setting. (And doing two decode passes sacrifices all time and memory benefits of using scale_denom in the first place.)

The problem is that the libjpeg architecture doesn't allow for that. It assigns one and only one DCT module to each component. The choice of SIMD vs. C, floating point vs. integer, and "fast" vs. accurate integer is baked into that assignment. Thus, we would have to make uncomfortable assumptions about which unscaled IDCT to use for the edge blocks, and we would have to allocate a separate output buffer for them. The additional changes to the architecture necessary to make this work would be disruptive and error-prone. Generally speaking, I am not interested in sweeping libjpeg API/architecture changes. Every time I try to poke around at that low of a level, ten things break unexpectedly. (People are still, as of a few months ago, finding unexpected issues with the partial decompression feature that Google submitted 11 years ago.) 

> Maybe libjpeg-turbo could grow a `scale_denom_border_resampling` bool setting to opt in to this behavior, and it setting some macro in a header (`JPEG_LIB_HAVE_SCALE_DENOM_BORDER_RESAMPLING` or what) that client code could check for to see if it that config toggle exists. (This would prevent every user of libjpeg-turbo having to autoconf for it.) If it's set, libjpeg-turbo would do the full-decode for the two right/bottom-most tiles and resampling as described above.
> 
> With this, viewers could use scale_denom for all JPEG images.
> 
> Would a PR around these lines have chances of being accepted?

Unfortunately no. It will take well into 2027 before expected project funding catches up to the labor spent developing 3.2, so I can't consider any major unfunded development right now. (Even if you submit a PR, it will take significant labor to test, clean up, document, and integrate it.) Furthermore, per above, disruptive modifications to the libjpeg architecture always bite me in the butt. I would rather use the TurboJPEG API for future extensions and treat the libjpeg API as more or less a legacy. I will make exceptions to that if the feature is really compelling, but in this case, the IDCT scaling feature has always worked the way it works. I strongly suspect that that feature predates the encoders that are filling in the edge blocks with black, and there's a very good argument to be made that such encoders are incorrect. Furthermore, IDCT scaling isn't as critical of a feature as it once was, so it doesn't make sense to significantly disrupt libjpeg-turbo to make that feature work better with encoders that are arguably incorrect.

There are ways to implement what you want externally to libjpeg-turbo. You would have to use the API functions that allow you to decode to raw DCT coefficients. Then you could call the IDCT, upsampling, and color conversion modules manually. It would be a pain, but it's possible. See the `tj3DecodeYUVPlanes8()` function in the TurboJPEG API for an example of calling the upsampling and color conversion modules manually.
