### ISSUE TITLE
Build on Mac check suggest

### ISSUE THREAD

**Issue by zeratel** [libjpeg-turbo/libjpeg-turbo#281] opened 2018-09-12 11:01 UTC
When I Build on my Mac (10.13.6) I have the following problems

[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make[2]: *** [simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[1]: *** [simd/CMakeFiles/simd.dir/all] Error 2
make: *** [all] Error 2

but my nasm is 2.13.03 , after my examination，I found the reason for the problem is in file 

CMakeCache.txt 
//NASM compiler
CMAKE_ASM_NASM_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/nasm

this nasm version is 0.98.40
my nasm is /usr/local/Cellar/nasm/2.13.03/bin/nasm

fix it problems is solving
So I hope that my experience is helpful for people who encounter this problem

**Comment by dcommander** [comment] 2018-09-12 16:19
A quick search of our issues for the keyword "macho64" reveals that this is a duplicate of #278.  

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md

"If using NASM, 2.10 or later (except 2.11.08) is required for an x86-64 Mac build"

**Closed by dcommander** 2018-09-12 16:19 UTC
