### ISSUE TITLE
Avoid duplication of jpeg_nbits_table between C and SIMD code

### ISSUE THREAD

**Issue by randomascii** [libjpeg-turbo/libjpeg-turbo#114] opened 2016-11-03 21:20 UTC
Changing some array declarations can shrink the size of the libjpeg-turbo read-only data segment by approximately 700 bytes.

In jmorecfg.h, specfically here:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jmorecfg.h#L368

there are four static const arrays defined. Because these are in a header file and this header file is included from multiple translation units the compiler ends up generating multiple copies of these arrays. In Chrome for Windows's chrome.dll and chrome_child.dll this results in four copies of each of these arrays being created (only three of rgb_pixelsize, for some reason). Each array is only 68 bytes, so the total waste is just (3 + 3 + 3 + 2) * 68 = 748 bytes per DLL, so not a big deal. But, arrays should not be defined in header files and this wastage is easily avoided. Just declare the arrays in a .c file tagged as "extern const" (otherwise the const implies static and they will not be visible to other translation units) and declare the arrays as "extern const" in the header file. Testing in chrome showed a savings of 752 bytes on the chrome_child.dll .rdata segment, and 656 bytes in the chrome.dll .rdata segment.

i.e.; 

mjorecfg.h:
extern const int rgb_red[JPEG_NUMCS];
extern const int rgb_green[JPEG_NUMCS];
extern const int rgb_blue[JPEG_NUMCS];
extern const int rgb_pixelsize[JPEG_NUMCS];

jdmaster.c:
extern const int rgb_red[JPEG_NUMCS] = {
	-1, -1, RGB_RED, -1, -1, -1, EXT_RGB_RED, EXT_RGBX_RED,
	EXT_BGR_RED, EXT_BGRX_RED, EXT_XBGR_RED, EXT_XRGB_RED,
	EXT_RGBX_RED, EXT_BGRX_RED, EXT_XBGR_RED, EXT_XRGB_RED,
	-1
};
...

Voila! No more duplication of data. This fix was tested with VC++ 2015 in a Chrome build and was found to save 1408 bytes across all .rdata segments. YMMV.

**Comment by dcommander** [comment] 2016-11-03 22:15
Yes, but there is a good reason not to do that, which is that moving the arrays into a .c file would change the ABI and create a backward ABI incompatibility with libjpeg and with prior versions of libjpeg-turbo.  At the moment, programs that build against libjpeg-turbo can still use libjpeg at run time, as long as the programs don't take advantage of any libjpeg-turbo-specific interfaces.  In fact, programs can even check for the existence of the libjpeg-turbo colorspace extensions at run time (refer to https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jcstest.c), thus allowing those programs to run on systems that provide either libjpeg or libjpeg-turbo as the system-installed JPEG library.  (Note that all of the above primarily applies to Linux, not Windows.)

If I did what you proposed, then it would mean that any program built against libjpeg-turbo would have to use only that version of libjpeg-turbo or newer at run time.  That runs counter to our mission of providing full backward ABI compatibility with libjpeg.  Also, it could create the potential for buffer overruns if the value of `JPEG_NUMCS` changed.  Let's say a program was built against a modern version of the libjpeg-turbo SDK that defines `JPEG_NUMCS` to be 17.  Currently, that program can still use an older version of libjpeg-turbo at run time, because if the program tries to set the colorspace to a value that the older libjpeg-turbo version doesn't support, the libjpeg API will trigger a run-time error that the program can trap.  With your proposal, attempting to use an older libjpeg-turbo version at run time would create a buffer overrun if the program attempted to use a colorspace extension that the older version didn't support.  No bueno.  Adding the arrays to the ABI would have to be done using symbol versioning, and their version would have to be incremented whenever `JPEG_NUMCS` changed.  It would be a pain in the butt.

If I had it to do over again, I probably should have put the rgb_* convenience arrays in jpegint.h instead of jmorecfg.h, but the libjpeg-turbo colorspace extensions have been around for 6 years now, so that interface is pretty much a de facto standard at this point.  I don't get paid for my work on libjpeg-turbo unless someone is specifically paying me for a project, so I'm generally only interested in spending time on stuff that affects quality in some tangible way.  I definitely want to keep the community happy, but I just can't go down every rabbit hole that people ask me to go down, or I'd be starving on the streets pretty quickly.

That being said, if you're using x86[-64], then there is a much lower-hanging piece of fruit in terms of reducing the size of the data segment.  I would really like to figure out how to make the SSE2- and AVX2-accelerated Huffman routines re-use the jpeg_nbits_table array from the C code.  Currently the SIMD-accelerated versions have their own local copy of that array, which adds 64k to the data segment.

**Comment by randomascii** [comment] 2016-11-03 23:42
Thanks for the explanation.  I'm not totally clear on why the out-of-range colorspace would not be trapped after my suggested change, but I trust you.

**Comment by dcommander** [comment] 2016-11-04 00:08
It has to do with a potential mismatch between the value of `JPEG_NUMCS` in the header and the value of that constant within the compiled library.  If I implemented this change, then the rgb_\*[] arrays in the current version of the libjpeg-turbo library would have a size of 17, but if I later added a colorspace, then the value of `JPEG_NUMCS` would increase, and any programs built against that future version of libjpeg-turbo would expect the rgb_\*[] arrays within the library to have a larger value as well.  So if a future program, built against the future version of libjpeg-turbo with `JPEG_NUMCS` defined as 18, was run against a current version of libjpeg-turbo with `JPEG_NUMCS` defined as 17, that future program would cause a buffer overrun if it tried to access rgb_red[17].  And since there is no way for a program to determine which value of `JPEG_NUMCS` was compiled into a particular version of the library, there is no way to guard against this overrun.  That's why it's a good idea to keep the rgb_\*[] static arrays in the same place as the `JPEG_NUMCS` definition.  Ensuring backward ABI compatibility means that any program compiled against a future version of the library should still work with a current version of the library, as long as it doesn't use any features that are only available in the future version.  It also means that, if the program does use features that are only available in the future version, then it should fail gracefully and predictably if run against a current version of the library.  (A buffer overrun isn't graceful or predictable.)

I freely admit that the rgb_\*[] arrays were something of a hack, but they were meant to work around a much nastier hack.  In libjpeg, traditionally you could not compress from/decompress to RGBA, BGR, BGRA, ABGR, or ARGB buffers unless you changed the value of the `RGB_RED`, `RGB_GREEN`, `RGB_BLUE`, and `RGB_PIXELSIZE` macros and rebuilt the library.  These arrays were my attempt to provide a similar type of static interface, so programmers could easily replace any existing references to (for instance) `RGB_RED` with `rgb_red[your_colorspace_of_choice]`.

**Comment by randomascii** [comment] 2016-11-04 00:09
Got it. And of course it makes perfect sense.

**Comment by msdsgn** [comment] 2018-10-23 17:48
Hello. I am sorry to bring this thread back from the dead, but I searched for help in reducing waste from my executable files related to `jpeg_nbits_table` because I noticed that in my .map file that `jpeg_nbits_table` was in the executable twice back in JPEG turbo versions 1.x, but now since 2.0 has been released with AVX2 instructions, `jpeg_nbits_table` now exists in my executable three times which means 128K is being wasted. Now granted, it is not much at all in a world of gigabytes of RAM and storage space, but if every library was wasteful like that, then the amount of 'bloat' is going to be astronomical! It would be nice if the compiler/linker could just optimise that out really, but I guess my compiler is not smart enough yet! It would be nice if something could be done to roll all that into one global lookup table though!

_MSVisual C++ 19.13.26128 x64_

**Comment by dcommander** [comment] 2018-10-23 18:02
@msdsgn if you want movement on that issue, then figure out how to share the array between assembly and C.  I spent hours trying to do that and was unable to.

**Comment by dcommander** [comment] 2018-10-26 15:38
NOTE: Refer to discussion in [Mozilla bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1501523).  My major problem with upstreaming the Mozilla patch at the moment is that it doesn't assemble properly for 32-bit Mac.

**Comment by dcommander** [comment] 2020-06-26 02:01
Since 32-bit Mac support is being eliminated from libjpeg-turbo 2.1.x, I am willing to reconsider this feature if someone can make it work using the code in the dev branch.

**Comment by dcommander** [comment] 2020-10-23 20:53
Refocusing this issue to the duplication of `jpeg_nbits_table`.

**Comment by mattleibow** [comment] 2023-08-23 21:04
Looking at this, can we not have a condition around this? So we can define the value in the header but have it conditioned so it can be as a const OR an external?

My C is a bit rusty, but will this maybe be possible?

jpeg_nbits_table.h:

```h
#ifdef EXTERN_NBITS_TABLE
extern const unsigned char jpeg_nbits_table[65536];
#else
static const unsigned char jpeg_nbits_table[65536] = {
   0,  1,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,
...
};
#endif
```

jpeg_nbits_table.c:

```cpp
#ifdef EXTERN_NBITS_TABLE

// temporarily undefine so we can include directly
#undef EXTERN_NBITS_TABLE
#include "jpeg_nbits_table.h"
#define EXTERN_NBITS_TABLE

#endif
```

**Comment by mattleibow** [comment] 2023-08-23 21:08
I am not needing compatibility as I am statically linking this with my project, so a smaller result is a bit better than compatibility with nothing.

**Comment by dcommander** [comment] 2023-08-23 21:25
@mattleibow The problem is not in C.  The problem is in the assembly code.  Mozilla had a patch that worked with libjpeg-turbo 2.0.x and prior, but the Huffman encoder changes in libjpeg-turbo 2.1.x broke it.  Now it will be necessary to fix it both with the Arm and x86 SIMD extensions, as well as run a complete battery of benchmarks to ensure that performance has not regressed.  (The SIMD Huffman encoder is sensitive to changes in memory layout.)  That's a significant effort, and I haven't had time to tackle it yet.

**Comment by mattleibow** [comment] 2023-08-23 23:15
Re-reading the comments here and I think I see what you mean.

**Closed** 2024-01-16 22:53 UTC
Labels: enhancement, help wanted
