### ISSUE TITLE
tjCompressFromYUV/tjDecompressToYUV performance

### ISSUE THREAD

**Issue by digi-chris** [libjpeg-turbo/libjpeg-turbo#354] opened 2019-05-08 09:23 UTC
I have a stream of YUV 422 images that I'd like to compress to JPEG and then decompress back to YUV 422. I was figuring I could use the TurboJPEG functions tjCompressFromYUV and tjDecompressToYUV to acheive this. I'd been assuming I would get better performance as this approach would skip the conversion to/from RGB.

I'm surprised to see that using these functions seems to be slightly quicker to compress, but is slower to decompress compared to using the standard TurboJPEG functions that work with the RGB colorspace.

Using tjbench, I get the following results.

**Standard compression**
```
tjbench maxresdefault_full.ppm 80 -subsamp 422

>>>>>  BGR (Top-down) <--> JPEG 4:2:2 Q80  <<<<<

Image size: 1920 x 1080
Compress      --> Frame rate:         37.712809 fps
                  Output image size:  180043 bytes
                  Compression ratio:  34.551746:1
                  Throughput:         78.201282 Megapixels/sec
                  Output bit stream:  54.319419 Megabits/sec
Reference image written to maxresdefault_full_422_Q80.jpg
Decompress    --> Frame rate:         49.228847 fps
                  Throughput:         102.080937 Megapixels/sec
Compression error written to maxresdefault_full_422_Q80_full-err.ppm.
```

**YUV Compression**

```
tjbench maxresdefault_full.ppm 80 -subsamp 422 -yuv

Testing YUV planar encoding/decoding

>>>>>  BGR (Top-down) <--> JPEG 4:2:2 Q80  <<<<<

Image size: 1920 x 1080
Encode YUV    --> Frame rate:         261.196908 fps
                  Output image size:  4147200 bytes
                  Compression ratio:  1.500000:1
                  Throughput:         541.617909 Megapixels/sec
                  Output bit stream:  8665.886539 Megabits/sec
Comp from YUV --> Frame rate:         39.209840 fps
                  Output image size:  180043 bytes
                  Compression ratio:  34.551746:1
                  Throughput:         81.305523 Megapixels/sec
                  Output bit stream:  56.475657 Megabits/sec
Reference image written to maxresdefault_full_422_Q80.jpg
Decomp to YUV --> Frame rate:         37.131739 fps
                  Throughput:         76.996374 Megapixels/sec
YUV Decode    --> Frame rate:         323.391467 fps
                  Throughput:         670.584546 Megapixels/sec
Compression error written to maxresdefault_full_422_Q80_full-err.ppm.
```

You can see in the results above the decompressing to RGB results in an fps of 49, whereas decompressing to YUV gives 37fps.

Is this expected behaviour? Is there any thing I can do to speed up the decompression process?

**Comment by dcommander** [comment] 2019-05-08 15:36
It works fine for me.  Here are my results from a 3.0 GHz Core i7:

```
> ./tjbench ~/test_images/artificial.ppm 95 -rgb -quiet

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Image  Image   Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  GRAY     95    3072   2048    348.8   24.13   323.5   

RGB  (TD)  4:2:0    95    3072   2048    248.5   18.75   318.8   

RGB  (TD)  4:2:2    95    3072   2048    204.4   16.70   271.0   

RGB  (TD)  4:4:4    95    3072   2048    149.6   14.30   219.4   
```

```
> ./tjbench ~/test_images/artificial.ppm 95 -rgb -quiet -yuv

Testing YUV planar encoding/decoding

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Image  Image   Encode  Comp    Comp    Decomp  Decode
Format     Subsamp  Qual  Width  Height  Perf    Perf    Ratio   Perf    Perf

RGB  (TD)  GRAY     95    3072   2048    1778    391.8   24.13   497.6   800.4

RGB  (TD)  4:2:0    95    3072   2048    1086    298.2   18.75   402.7   1686

RGB  (TD)  4:2:2    95    3072   2048    1032    232.0   16.70   315.7   1545

RGB  (TD)  4:4:4    95    3072   2048    943.8   162.8   14.30   239.3   1482
```

(artificial.ppm is available here: http://imagecompression.info/test_images/rgb8bit.zip)

However, it should be noted that the test image I'm using has an image width that is evenly divisible by 8.  If the image width isn't evenly divisible by 8 * {scaling_factor} (== 8 in this case, since you aren't using decompression scaling), then `tjDecompressToYUVPlanes()` has to decompress into an intermediate buffer and copy the decompressed rows into the output buffer.  This decreases the performance of YUV decompression significantly.  On my machine, the performance of YUV decompression is reduced to the same level as full decompression, but it's possible that your machine-- or something about your specific image-- makes it slower.

**Comment by dcommander** [comment] 2019-05-08 16:03
A further limitation with images that use 2X horizontal chroma subsampling (4:2:2, 4:2:0, etc.) is that the Y image plane has to have a width that is evenly divisible by 2.  For a W x H 4:2:2 JPEG image, the planes will have the following dimensions:

(W2 = W rounded up to the nearest multiple of 2 = (W + 1) & (~1))

Y:  W2 x  H
Cb, Cr:  (W2 / 2) x H

Also, with horizontally-subsampled images, the MCU width for the Y plane is 16, not 8.  So in this case, the fast path will be used for the Y plane if (W2 % 16) == 0, and it will be used for the chroma planes if (W2 / 2) % 8 == 0.

A possible improvement upon this would be to take into account the `strides[]` parameter, which allows the caller to specify the alignment of each row in each output plane.  Even if the JPEG image itself did not have MCU-aligned rows, it should still be possible to use the fast decompression path if the output strides are MCU-aligned.

**Comment by dcommander** [comment] 2019-05-08 16:20
NOTE: several edits above, as I was refreshing my memory as to the terminology.

**Comment by digi-chris** [comment] 2019-05-09 08:31
Thanks for the response and additional information - the file I was using was 1920 x 1080, so I thought should decompress quite well.

Anyway, I re-ran the tests using the artificial.ppm file. I ran them last night and the YUV decomp to 422 and 444 was still slower (computer here is a core i7 2.6 GHz). Tested on another machine, and this showed results more in-line with your results.

I tested again this morning on the original machine and got the following:

```
tjbench artificial.ppm 95 -rgb -quiet

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Image  Image   Comp    Comp    Decomp
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf

RGB  (TD)  GRAY     95    3072   2048    89.16   24.13   58.31

RGB  (TD)  4:2:0    95    3072   2048    64.87   18.75   86.87

RGB  (TD)  4:2:2    95    3072   2048    54.32   16.70   71.00

RGB  (TD)  4:4:4    95    3072   2048    38.65   14.30   54.33
```

```
tjbench artificial.ppm 95 -rgb -quiet -yuv

Testing YUV planar encoding/decoding

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Image  Image   Encode  Comp    Comp    Decomp  Decode
Format     Subsamp  Qual  Width  Height  Perf    Perf    Ratio   Perf    Perf

RGB  (TD)  GRAY     95    3072   2048    967.5   93.06   24.13   92.54   121.4

RGB  (TD)  4:2:0    95    3072   2048    572.3   70.00   18.75   87.62   927.4

RGB  (TD)  4:2:2    95    3072   2048    528.5   51.34   16.70   77.19   890.7

RGB  (TD)  4:4:4    95    3072   2048    548.7   42.77   14.30   60.11   822.0
```

So, this time I'm seeing the results I'd expect. I still can't quite understand how it was previously slower, but it must be some sort of local condition causing the issue, although since I was running these tests one after the other, and I got similar results repeatedly, I'm a bit baffled as to what was going on.

I'll keep testing and see if I can repeat the problem.

**Comment by dcommander** [comment] 2019-05-09 13:35
Interesting.  You can improve the reproducibility of TJBench results by using the `-warmup` option, but otherwise, I have no explanation.  1920x1080 should definitely be using the fast path.

**Comment by dcommander** [comment] 2019-05-09 13:36
Closing for now, but feel free to update the issue with further information when you have it.

**Closed by dcommander** 2019-05-09 13:36 UTC
Labels: question
