### ISSUE TITLE
Is jpeg_crop_scanline() supported in buffered-image mode?

### ISSUE THREAD

**Issue by derselbst** [libjpeg-turbo/libjpeg-turbo#611] opened 2022-07-24 12:44 UTC
Considering the following code

```c++
jpeg_create_decompress();
jpeg_read_header();
cinfo.buffered_image = true;
jpeg_start_decompress();
jpeg_crop_scanline();
```

the call to `jpeg_crop_scanline()` would fail, because the library is expected to be in SCANNING state:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/a405519e961aeee3096f7bff45be6330dfa054b8/jdapistd.c#L166-L167

However, when `buffered_image` is true, `jpeg_start_decompress()` puts the library into BUFIMAGE state:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/a405519e961aeee3096f7bff45be6330dfa054b8/jdapistd.c#L52

causing `jpeg_crop_scanline()` to complain. When reading through the docs, I couldn't find that this is a documented limitation. So I do wonder whether this behavior is actually intended? Esp. because when I manipulate the state, like

```c++
cinfo.global_state = 205;
jpeg_crop_scanline();
cinfo.global_state = 207;
```

the call to `jpeg_crop_scanline()` succeeds and the library is decoding the partial scanlines as expected.

**Comment by dcommander** [comment] 2022-07-24 14:23
The partial image decompression features in the libjpeg API were originally implemented by Google as a way for them to support the higher-level partial image decompression APIs in the Android O/S. Unfortunately partial image decompression was not sufficiently tested with the more esoteric features of the libjpeg API, so this isn’t the first oversight that has popped up over the years. I’ll look into it. It may simply be that the code works fine in buffered image mode, as you observed, but the implementer didn’t realize that `DSTATE_BUFIMAGE` was also a valid decompression state.

**Comment by dcommander** [comment] 2022-07-28 21:43
With buffered image mode, you are supposed to call `jpeg_start_output()` and `jpeg_finish_output()` in a loop between the calls to `jpeg_start_decompress()` and `jpeg_finish_decompress()`.  Unless I miss my guess, `jpeg_crop_scanline()` will work properly with buffered image mode if the function is called after `jpeg_start_output()`.  Can you confirm?  If that is the case, then the documentation simply needs to be updated.

**Comment by derselbst** [comment] 2022-07-30 11:52
> you are supposed to call jpeg_start_output() and jpeg_finish_output() in a loop between the calls to jpeg_start_decompress() and jpeg_finish_decompress()

Yes, that's what I do. Looping until `jpeg_input_complete()`, limited to 1000 iterations as you advised in that Mozilla paper.

For some images, I'm getting a `JERR_BAD_VIRTUAL_ACCESS` when zooming in too far. Currently trying to understand where this is coming from, working on getting a stacktrace, which is a bit tricky because I'm bound to Windows at the moment. So, pls. give me a few more days to check this. I'll keep you posted.

**Comment by derselbst** [comment] 2022-08-02 18:52
Ok, so the `JERR_BAD_VIRTUAL_ACCESS` is somehow related to `jpeg_skip_scanlines()`, but it doesn't matter, whether `cinfo.two_pass_quantize` is true or false. When I comment out that call the error isn't raised. I will set up a standalone demo program to figure out if this is a problem in my image viewer or elsewhere.

In any case, it's not related to this issue and I can confirm that `jpeg_crop_scanline()` works fine in buffered image mode, for all the big, small, progressive and non-prog JPEGs I've tested. So I would be happy if you could simply update `jpeg_crop_scanline()` to permit the `DSTATE_BUFIMAGE` state as well.

**Comment by dcommander** [comment] 2022-08-02 20:16
You missed the point of my previous comment, which is that it shouldn't be necessary to update `jpeg_crop_scanline()` to handle `DSTATE_BUFIMAGE`.  I think you just need to move the call to `jpeg_crop_scanline()` inside of the `jpeg_start_output()`/`jpeg_finish_output()` loop.  The state will be `DSTATE_BUFIMAGE` between the call to `jpeg_start_compress()` and the call to `jpeg_start_output()`, but it should be `DSTATE_SCANNING` after `jpeg_start_output()` is called.  Can you confirm?

And yes, a standalone program would be appreciated.  I am flying blind here.

**Comment by derselbst** [comment] 2022-08-03 07:31
> I think you just need to move the call to jpeg_crop_scanline() inside of the jpeg_start_output()/jpeg_finish_output() loop.

Sry, missed that indeed.  I can confirm that this works well for non-progressive images.

For progressive images, one would need to ensure to only call `jpeg_crop_scanline()` _once_ when running the loop. That's because the first call would manipulate `cinfo.output_width`, causing the second call to `jpeg_crop_scanline()` to fail with `JERR_WIDTH_OVERFLOW` here:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/59337a67b1cf47a74cf1415c7445fed4275a5d5e/jdapistd.c#L173-L174

In any case, I find this solution too inconvenient though,  because in my case I need to respect the `xoffset` returned by `jpeg_crop_scanline()` when doing the buffer setup for `jpeg_read_scanlines()` -  but this setup is done outside of the `jpeg_start_output()`  / `jpeg_finish_output()` loop.

Hence I would prefer to stay with the `global_state` manipulation mentioned initially. Or making `jpeg_crop_scanline()` more permissble ;)

> And yes, a standalone program would be appreciated. I am flying blind here.

Sure, I'll start working on it.

**Comment by derselbst** [comment] 2022-08-07 19:57
The demo is ready, I'd be glad if you could have a look at it: [jpeg-test.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/9277362/jpeg-test.zip)

It's basically the logic that I use in my viewer. Compiling should be as simple as `c++    -g -o test  jpeg-test.cpp -ljpeg`

There are also two test images included. `bird_prog.JPG` is a progressive version of the original `bird.JPG` (though _any_ other progressive and non-prog image should do as well).

Tested with jpegturbo 2.1.3:

When running `./test bird.JPG` you should get "Bogus virtual array access".
When running `./test bird_prog.JPG` you should get "JPEG decoding completed successfully."

When changing the `skipScanlinesTop` to zero, it should run successfully with any image, because this will effectively make `jpeg_skip_scanlines()` a no-op.

Changing `offsetX` to zero would avoid the call to `jpeg_crop_scanline()` and should have no effect on any of the above cases. But it demonstates how I use the cropping and why it would be inconvenient to postpone the call after `jpeg_start_output()`. Yet, if you do postpone it, it will work fine for the `bird.JPG` but for `bird_prog.JPG` it would fail when called the second time.

Pls. let me know if you prefer to open a new ticket for the "Bogus virtual array access", as it seems to be linked to `jpeg_skip_scanlines()`. Unless, I'm doing something wrong?

**Comment by dcommander** [comment] 2022-08-08 14:11
> It's basically the logic that I use in my viewer. Compiling should be as simple as `c++ -g -o test jpeg-test.cpp -ljpeg`

It isn't, unfortunately.  I cannot find a single version of GCC, including as recent as GCC 12, that successfully compiles this program.

**Comment by dcommander** [comment] 2022-08-08 15:21
I'm looking into the "Bogus virtual array access" error.  It seems interrelated with #613, which I thought I had fixed but apparently not.  All of this partial image decompression stuff was contributed by Google in support of the higher-level partial image decompression APIs in Android.  The feature works fine for their intended use case, but unfortunately it didn't take into account some of the more esoteric libjpeg modes, including buffered-image mode.  This is why I am very hesitant to accept enhancements that deeply affect the libjpeg API.  The design of that API was necessitated by limited memory models (MS-DOS, etc.), and that makes it unnecessarily complex by today's standards.

**Comment by dcommander** [comment] 2022-08-08 16:36
Correction: The issue is unrelated to #613, because it exists in the 2.0.x code base as well.  It's apparently an incompatibility between `jpeg_skip_scanlines()` and buffered-image mode that has existed since that function was introduced.  Ugh.

**Comment by dcommander** [comment] 2022-08-08 21:07
Should be fixed in main.  Please verify the fix as soon as you can, as I would like to release libjpeg-turbo 2.1.4 by the end of this week.

**Closed** 2022-08-08 21:07 UTC

**Comment by derselbst** [comment] 2022-08-09 08:00
Great! I can confirm that this fixes the Bogus access error and allows me to `crop_scanline` without manipulating the global state. Thank you very much!
