### ISSUE TITLE
Compiling into a small binary (decoder only)

### ISSUE THREAD

**Issue by photopea** [libjpeg-turbo/libjpeg-turbo#431] opened 2020-05-17 21:12 UTC
Is it possible to compile libjpeg-turbo into a binary (decoder only, baseline and progressive), which is small (e.g. under 60 kB, or under 20 kB after ZIPping)?

I would like to compile it to WebAssembly, so we can omit parallelism and CPU-specific parts (SIMD, assembly code, etc).. I am using [nothingjs](https://github.com/nothings/stb/issues/964#issuecomment-628249207) now, but I thought it could be made faster, or use less memory.

At the moment, libjpeg-turbo feels like a huge library with a very complex build process. Would it be hard to prepare a build script, which extracts a "light" decoder out of it? We plan to use it at [Photopea.com](//www.Photopea.com), where users decode about 100 000 JPGs every day.

**Comment by dcommander** [comment] 2020-05-18 00:27
Duplicate of #429. Refer to the answer in that issue. As far as the library being “huge” and “very complex”, if you have concrete suggestions for how to improve it, offer those concrete suggestions, but hyperbole is not helpful. I’ve donated hundreds of thousands of dollars in free labor to this project over the past 10 years, and the result is certainly much more performant and less complex than its predecessor. Yet people still complain about something they are getting for free.

libjpeg-turbo is a codec. The “co” part of that means “compressor.” Thus, removing the compressor is not in any way supported. If people want to do that, it’s incumbent upon them to figure it out. And yet I provided a huge hint in #429. That is the limit of what I can do here.

**Closed by dcommander** 2020-05-18 00:27 UTC
Labels: enhancement
