### ISSUE TITLE
regression 3.0.3: jpeg_std_message_table unexported, breaking rawtherapee run-time and compilation

### ISSUE THREAD

**Issue by mandree** [libjpeg-turbo/libjpeg-turbo#767] opened 2024-05-28 20:34 UTC
Greetings,

libjpeg-turbo release 3.0.3 broke compilation and execution of rawtherapee 5.10.

The commit https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586 resulted in this:

https://github.com/libjpeg-turbo/libjpeg-turbo/blame/9ddcae4a8f4aaa096ccdcddec36afc52fbc01481/jerror.c#L49

...and essentially made the jpeg_std_message_table a "static", i. e. unexported, data structure, while the comment immediately before it still claims it were exported in case somebody else wanted to refer to it:

https://github.com/libjpeg-turbo/libjpeg-turbo/blame/9ddcae4a8f4aaa096ccdcddec36afc52fbc01481/jerror.c#L43

See https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586#r142486730

On FreeBSD 14, and probably all other systems, upgrading libjpeg-turbo from 3.0.2 to 3.0.3 without adding a workaround and recompiling rawtherapee also breaks a pre-installed rawtherapee and prevents it from starting:

```
$ rawtherapee
ld-elf.so.1: /usr/local/bin/rawtherapee: Undefined symbol "[jpeg_std_message_table@LIBJPEG_8.0](mailto:jpeg_std_message_table@LIBJPEG_8.0)"
```

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279371

**Comment by dcommander** [comment] 2024-05-28 21:08
Duplicate of #763.  It broke RawTherapee because RawTherapee was incorrectly relying upon an internal array that never should have been exposed in the first place (and, in fact, it wasn't exposed on all platforms.)  RawTherapee has since corrected their code.  In the future, please search existing issues before filing a new one.

**Closed by dcommander** 2024-05-28 21:07 UTC

**Comment by mandree** [comment] 2024-05-28 21:10
Yeah. You don't go change exported symbols without bumping major revision.

**Comment by mandree** [comment] 2024-05-28 21:12
> Duplicate of #763. It broke RawTherapee because RawTherapee was incorrectly relying upon an internal array that never should have been exposed in the first place (and, in fact, it wasn't exposed on all platforms.) RawTherapee has since corrected their code. In the future, please search existing issues before filing a new one.

It did search and did not find it. The source code comment, as shown, marked the export of the default table as intentional. Gotta seek out FreeBSD decision on whether we need to strip out jpeg-turbo because it is maintained in a non-reliable way with patchlevel upgrades breaking run-time and compile-time compatibility.

**Comment by dcommander** [comment] 2024-05-28 21:35
Sorry you feel that way.  I exercise a ridiculous amount of caution when maintaining this project, and I make very little money doing so (certainly not enough to live on.)  Yet I constantly get bombarded with issues from all directions, and I am constantly faced with tough decisions regarding how to deal with those issues.  It never fails that I fix something because someone begs me to fix it, but doing so breaks something else.  That has been the case for the entire 14-year history of this project.  It is a very tough and thankless job, and I assure you that you don't want this job.  Approaching me with aggression and threats makes the job tougher, and it makes it a lot less likely that you're going to get what you want.

The RawTherapee developers themselves agreed that it was a bad idea for their software to refer to the symbol in question, so I'm not sure why you are fighting on their behalf.  If the symbol were part of a public API, then yes, it should not be changed without bumping the major revision.  It is not part of a public API (or any API, for that matter.)  In fact, it was never possible to access it on all platforms, because some platforms use a linker script that only exposes the documented symbols.  (That has also been the case for the entire 14-year history of libjpeg-turbo, as well as libjpeg before it.)  I did not actually notice the code comment until now, but you have to understand that this is 33-year-old code from the MS-DOS era.  Some things that the code did then do not make sense in 2024.  It is certainly not reliable for a calling program to refer to a symbol when that symbol's exposure is (a) only documented in a code comment and (b) not exposed on all platforms.  The RawTherapee developers already had to #ifdef around their reference to the symbol, because it was never exposed on Windows (for reasons previously stated.)  And there was actually no reason for their code to refer to it.  By modifying their code, they not only made it work properly with libjpeg-turbo 3.0.3 but also cleaned it up.

I am always receptive to logical arguments, but your arguments above are knee-jerk and threatening, and I am not receptive to that.

**Comment by dcommander** [comment] 2024-05-28 22:00
I am sympathetic to the argument that this breaks run-time compatibility with existing RawTherapee code bases, but even if I reverted https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586, it would still be August at the earliest before that change would land in an official release of libjpeg-turbo.

So really your options are:
1. Apply the upstream patch from RawTherapee to your RawTherapee package, thus making it compatible with libjpeg-turbo 3.0.3.
2. Revert your libjpeg-turbo package to 3.0.2, or revert https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586 in your libjpeg-turbo package, until you can upgrade to an official release of RawTherapee that includes their upstream patch.
- Assuming I agreed to revert https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586, apply the upstream reversion commit to your libjpeg-turbo package until you can upgrade to an official release of libjpeg-turbo that includes the reversion commit.

Going back in time isn't an option, so one way or the other, you're going to have to patch something temporarily.  IMHO, the best course of action would be to temporarily patch RawTherapee with the understanding that a future release of RawTherapee will resolve this issue.

**Comment by dcommander** [comment] 2024-05-28 22:24
To put it another way, what if I had removed the code comment?  It wouldn't have changed the API, would it?  It is impossible for a library to keep internal symbols unchanged for perpetuity.  On many occasions, I have had to extend the internal structures in **jpegint.h** in order to add features and even fix bugs.  It is thus understood that the symbols referenced in **jpegint.h** are internal and subject to change without notice.  `jpeg_std_message_table[]` is not even on the same level as the symbols referenced in **jpegint.h**, because it is not even exposed in a header (internal or otherwise.)

Another argument: On some platforms, `jpeg_nbits_table[]` (another internal table) was also an unintentionally exposed symbol, and it was possible that calling applications could have (unwisely) referred to it.  However, that symbol would not exist on Arm platforms, since a compiler intrinsic (rather than a LUT) is used for bit counting on those platforms.  Similarly, `jpeg_std_message_table[]` was never accessible on Windows, because the symbol was never exposed in the DLL .def file (and that was the case before libjpeg-turbo ever became a project.)  RawTherapee recognized that limitation, which is why they #ifdef'ed around their reference to `jpeg_std_message_table[]`.  They should have actually done the right thing and removed the reference on Un*x as well, but they were not prompted to do so until libjpeg-turbo 3.0.3 broke their builds.

**Comment by dcommander** [comment] 2024-05-28 22:30
Your argument is: libjpeg-turbo should revert https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586, because there is a code comment that says that `jpeg_std_message_table[]` is an external symbol.

My argument is: That code comment was actually a work of fiction, and RawTherapee only worked by accident, so the solution is really to remove the code comment so that no other applications make the same mistake.

I would be more receptive to your argument if other applications were known to be affected or if there was not a readily-available fix for the application in question.  Otherwise, it seems that https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586 made libjpeg-turbo's behavior more reliable, not less, because it unexposed the undocumented internal symbol on all platforms rather than only exposing it on some platforms.

**Comment by mandree** [comment] 2024-05-28 22:56
Thanks for taking the time to respond more thoroughly on the issue, and my apologies offered herewith if my earlier messages were perceived as inadequate, I did not mean abuse, but wanted to express that some other project (FreeBSD, and its ported third-party software collection) may want to avoid such surprises in the future.

In the meanwhile, I had committed a trivial workaround to just call the default setup function and steal the table pointer though the official interface, and my build system is testing a cherry-pick of the upstream RawTherapee PR 7080 to replace that, so we'll be closer to what they're going to do with their future v5.11, essentially implementing your suggestion "1."


I certainly support that the source code comment needs revision now that the code has changed and your intention is clear on that, and yes, consistency is generally appreciable, with the remarks detailed below.


Technically, removing any symbol from a library - irrespective of whether the export was intentional, consistent, or not - makes the library incompatible with all users, as seen.
In this case, we've seen API break (compiler may warn, linker errors out), which is more obvious, and ABI break, which is a painful part because the library upgrade breaks a previously working application, and that's astonishing.

This also is not a request about a particular application, but a request of being able to decouple application and library upgrades as far as this would be "typical" use, say, we only change patchlevel release numbers, within, say, 3.0.x, where applications consuming the library are not routinely prepared to deal with API or ABI changes.
 
I also understand the item that this unintentional export was not to be considered part of some contract - but the technical breakage happens irrespective of the political/contractual/intentional considerations, and it seems that all rolling-release distros that have upgraded libjpeg-turbo are now cleaning up the mess and cherry-pick the RawTherapee upstream change, or find other solutions.

In such situations, it really helps to make that newly introduced incompatibility obvious to everyone and everything.  Suggest: Through the release notes, and also technically, for instance, by bumping the library's major version, or name, because that also makes it easier to keep "old" and "new" version installed if compatibility with a variety of applications demands so.
So, if any exported symbol changes semantics, arguments, or gets removed, it is helpful to bump library major version, from libfoo.so.4 to libfoo.so.5. Or distribution "advertised" version from 3.0.2 to 4.0.0.

I understand your reasoning that you don't want to consider an inadvertent export a contract - but technically, we still got things broken.


I also understand what the feelings may be - I have been packaging third-party stuff (among that, rawtherapee) for FreeBSD for many years. For even longer, I have been the upstream and - these days - sole maintainer of two and a half upstream projects I've inherited or co-founded (the "half" one referring to Usenet which is dying out anyways), so I know what's on, but I admit my software is application stuff, not a library, so the capture cross section is smaller, and Windows means "Cygwin", so that's my relief. All these three date back to 1995...2003 with their respective oldest commits. https://xkcd.com/2347/ pretty much sums it up for libraries.

**Comment by dcommander** [comment] 2024-05-29 03:56
I love that cartoon, particularly since I started developing open source software professionally in 2003.  :)  I understand that the end result was unintended pain on the part of downstream distributors and developers of one specific application, but there was no way I could have foreseen that.  Two months elapsed between the time that https://github.com/libjpeg-turbo/libjpeg-turbo/commit/34c055851ecb66a2d9bee1a3318c55cd9acd6586 was pushed and 3.0.3 was released.  Unfortunately, however, most downstream user-developers and distributors don't bother to test the tip of the main branch until it is officially released, so issues like this don't get detected until it is too late to fix or even document them.  RawTherapee was doing something that even they admit was a hack, and I could not have imagined that any application would do that (in part because it wasn't even remotely necessary, and also because it wouldn't have worked on all platforms.)  Had I foreseen the commit to be anything other than innocuous, I wouldn't have pushed it, or I would have deferred it until 3.1 beta. (However, I should also mention that few downstream user-developers and distributors bother to test beta releases.)  Actually, had I noticed that comment, I wouldn't have pushed the commit.  What's done is done, however.  Suffice it to say that, because the libjpeg API is so old and complicated, people have figured out every possible way to abuse it over the years.  I promise that I'm trying really hard to fix things, not to break things.  Unfortunately, however, the only way to guarantee that nothing will ever break again is to never modify the library ever again.

I disagree that removing an unintended, undocumented, and unreferenced export makes the library backward-incompatible.  (In fact, there are [other implementations of the public libjpeg API](https://github.com/libjxl/libjxl/tree/main/lib/jpegli) that include none of those internal symbols.)  Compatibility is defined by the public API/ABI.  Any application that accesses a symbol outside of that public API/ABI does so at its own risk.  It does seem as if Tom Lane intended `jpeg_std_message_table[]` to be exposed, so there is validity to the argument that it should have remained exposed.  However, it effectively already wasn't on Windows.  So my options are either to revert 34c055851ecb66a2d9bee1a3318c55cd9acd6586 and start exposing the symbol on Windows, which might create whiplash, or to simply remove the comment.  Since this is only known to affect RawTherapee and they have already fixed the issue downstream, I think the best course of action is to remove the comment.  It would confuse the issue to revert 34c055851ecb66a2d9bee1a3318c55cd9acd6586, and it would confuse it even more to start exposing the symbol on Windows.  (Note that the RawTherapee developers claim that the symbol used to be exposed on Windows in libjpeg-turbo 1.5.x.  I don't personally see how that is possible, however, because the DLL .def file never included it.)
