### ISSUE TITLE
EXC_BAD_ACCESS in iOS

### ISSUE THREAD

**Issue by Waishon** [libjpeg-turbo/libjpeg-turbo#146] opened 2017-03-25 20:41 UTC
Hi,

I'm currently trying to build the flexVDI App for iOS, which is using the spice-protoncol which implement your libjpeg-turbo library. 
I've build the library using cebero of https://github.com/flexVDI/cerbero which compiles the libjpeg-version of 1.4.1.

The problem is that the method 
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdsample.c#L98
is throwing an EXC_BAD_ACCESS error and the debugger shows, that the variables are null:
![bildschirmfoto 2017-03-25 um 21 35 50](https://cloud.githubusercontent.com/assets/7796567/24325907/44b2b394-11a3-11e7-8cbf-12a7699c9656.png)

Some methods before the cinfo-variable isn't null:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdapistd.c#L282
![bildschirmfoto 2017-03-25 um 21 39 22](https://cloud.githubusercontent.com/assets/7796567/24325925/8c80ab36-11a3-11e7-9f00-30f21b10c487.png)

But in the "process_data_context_main"-method called from the method mentioned above cinfo is null. 
![bildschirmfoto 2017-03-25 um 21 40 54](https://cloud.githubusercontent.com/assets/7796567/24325933/bfddf524-11a3-11e7-80fd-8807be6a07b6.png)

Might the "null" be the reason that the EXC_BAD_ACCESS-error is thrown, or why would that happen?

I would be glad if anyone give me an advice :)

**Comment by dcommander** [comment] 2017-03-26 15:45
I think I've run into that error before, but IIRC, it was because I was trying to run our official iOS binaries (which contain bitcode) on an older iOS release. If it doesn't have anything to do with bitcode, then I have no clue.

**Comment by Waishon** [comment] 2017-03-26 15:51
What do you exactly mean with "bitcode"?
I've compiled the library​s from source and using an iPhone simulator with iOS 10.2.

Another person run into the same issue when running this flexVDI-App, so it might be a problem of the flexVDI App, he guessed that it might be related to the encoding of the stream.

**Comment by dcommander** [comment] 2017-03-28 19:15
Bitcode is an intermediate cross-platform instruction set that newer iOS releases support:

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

I don't use the Xcode GUI, so I have no idea how to disable/enable bitcode in Xcode builds, but disabling it would be the first thing I would try.  If that doesn't work, then I have no idea.  libjpeg-turbo 1.4.1 is old, so this could very well be a libjpeg-turbo bug that has since been fixed, or it could be a new libjpeg-turbo bug, or it could be a flexVDI bug.  I strongly suspect the latter, because libjpeg-turbo is widely used in iOS apps, but no one else has reported this issue.

**Comment by dcommander** [comment] 2017-05-06 20:54
Note that the bitcode error was a red herring, and I apologize for the noise.  I reproduced that error just today, and the symptoms are completely different.  When the bitcode error occurs, iOS binaries on my jailbroken iPhone abort with "Killed: 9" until I run `ldid -S` on the binaries.  So unfortunately I've never run into this `EXC_BAD_ACCESS` error and have no clue what's causing it.

**Comment by dcommander** [comment] 2017-09-11 21:48
Closing as SEP.  There is no evidence that this is a libjpeg-turbo bug, given that other iOS applications are successfully using libjpeg-turbo.  Feel free to add additional information if it comes to light.

**Closed by dcommander** 2017-09-11 21:48 UTC
