### ISSUE TITLE
tjDecompressToYUV2 may decode wrong chorma data in the last line or row when image width or height is an odd number

### ISSUE THREAD

**Issue by jianliang79** [libjpeg-turbo/libjpeg-turbo#360] opened 2019-06-15 02:02 UTC
I have a picture which is produced by an OPPO phone's camera which is 3000x3000 in size, yuv 4:2:0. If I decode this picture with tjDecompressToYUV2() in 3/8 scaling factor(width/height will be 1125), the chroma data of the last line will be incorrect. It will show a green line in the bottom of the decoded image. I decode the picture like the following:
    tjDecompressToYUV2(
        decoderHandle,
        imageData,
        imageDataSize,
        outputBuffer,
        1125,
        4,
        1125,
        0);

    This issue happens only when the actual decoded size is odd number. In that case the last line of the chroma data will be incorrect but the luma data of the last line is correct. With other test picture(also 3000x3000, 3/8 scaling), The luma data of the last row may be also incorrect.
    I can produce this issue under Windows and Android with libjpeg-turbo 2.0.2. I think I can also reproduce this issue on other platform too but I didin't try it.

    BTW: If I decode this picture to RGBA at 3/8 scaling factor with tjDecompress2(), the result is correct.
    BTW: If I open this jpg file with GIMP and export it to a new yuv 4:2:0 jpeg image with the same size, tjDecompressToYUV2 can decode correct result with the new image at 3/8 scaling factor.

    The picture to reproduce this issue:
![wierd](https://user-images.githubusercontent.com/11371201/59545497-a1221880-8f51-11e9-9e6b-e489858d3c80.jpg)

**Comment by dcommander** [comment] 2019-06-28 17:10
I was able to reproduce the problem by running
```
tjbench {image} -scale 3/8 -yuv
```
I will investigate.

**Comment by dcommander** [comment] 2019-06-28 19:47
I could find no errors in the TurboJPEG API code, and a 3000x3000 JPEG test image that I created decoded with no problems.  Sorry, but I have no other ideas.

**Comment by dcommander** [comment] 2020-06-23 20:21
As near as I can determine, this problem is caused by invalid values in the test image.  My diagnostic process:

- Disable the libjpeg-turbo SIMD extensions (no effect)
- Disable the optimized Huffman decoder (no effect)
- Decompress the test image into a PPM file and recompress it using identical quality and subsampling parameters (Q95, 4:2:0).  The recompressed image decompressed to YUV without the artifact, but there was no difference between the `jpeg_decompress_struct` values generated by the recompressed image and the original test image.  Thus, as near as I could tell, the recompressed image and the original test image touched exactly the same libjpeg-turbo code paths.
- Remove all markers (including EXIF data) from the test image (no effect)
- Losslessly transform the test image in various ways prior to decompression:
    - Vertical flip, 180-degree rotation: The artifact remained on the bottom edge of the transformed image, which corresponded to the original top edge.
    - Transpose, 270-degree rotation: The artifact moved to the right edge of the transformed image, which corresponded to the original bottom edge.
    - Transverse, 90-degree rotation: The artifact moved to the right edge of the transformed image, which corresponded to the original top edge.
    - Grayscale: The artifact disappeared, which suggested that it was in one or more of the chroma planes.
- Re-compress the decompressed YUV planes using `tjCompressToYUV()` and then decompress the resulting JPEG image using `tjDecompress2()`.  The artifact remained.

Examining [the YUV values returned from `tjDecompressToYUVPlanes()`](https://github.com/libjpeg-turbo/libjpeg-turbo/files/4821349/59545497-a1221880-8f51-11e9-9e6b-e489858d3c80-yuvvalues.txt), I observed (as you did) that the values in the last row of the chroma planes were inconsistent with the values in the previous rows.  Disabling decompression scaling, I observed that some of the YUV values in the test image (including the first value in the last row) were 0, which is invalid.  Those 0 values were output from the IDCT algorithm, so they appeared to be the result of invalid values in the JPEG image itself.  It may simply be that the YCbCr-to-RGB conversion algorithm that is normally performed when decompressing a JPEG image corrects those values.

As near as I can determine, this isn't a bug in libjpeg-turbo.  Closing for now, but please feel free to comment if you have additional information.

**Closed by dcommander** 2020-06-23 20:21 UTC
Labels: bug
