### ISSUE TITLE
static jpeg_std_message_table broke build of rawtherapee

### ISSUE THREAD

**Issue by sthen** [libjpeg-turbo/libjpeg-turbo#763] opened 2024-05-12 12:00 UTC
In 34c0558, jpeg_std_message_table was made static. This breaks build of rawtherapee (https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/jdatasrc.cc#L251). Is rawtherapee doing this wrong or should it be fixed in libjpeg-turbo?

**Comment by dcommander** [comment] 2024-05-12 15:13
Rawtherapee is doing something wrong. Calling programs cannot rely on internal (unexposed) library symbols, which are subject to change without notice. (In fact, your code probably wouldn't have even worked with the libjpeg-turbo Linux shared library, in which symbol exposure is determined by the linker script.) I think the correct thing to do is to include **jerror.h** in such a way that a duplicate of the message table is created within the body of your code.

**Closed** 2024-05-12 15:13 UTC
Labels: bug

**Comment by sthen** [comment] 2024-05-12 19:00
Thanks. Not my software btw, I'm an OS packager and ran into the problem after updating libjpeg-turbo, I'll have a look at patching it and see if I can feed it upstream.

**Comment by mandree** [comment] 2024-05-28 21:26
I beg to differ on the "unexposed" account. This was a well-intended warning-removal approach gone wrong, and jpeg-turbo consumers were right in relying on that because the intention of the export was also there.

The source code comment still stands in 3.0.3 that the export of the default message table was intentional, and it was plastered with const keywords to make that safe:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/3.0.3/jerror.c#L39
with lines 43f this:

```
 * The message table is made an external symbol just in case any applications
 * want to refer to it directly.
```

**Comment by dcommander** [comment] 2024-05-28 21:38
A symbol is "exposed" when it is documented and in a header.  Otherwise, how could a calling application ever expect to refer to it reliably without reading the code? If you have to read the code to figure out how to refer to an external symbol,  then it's not part of an API.  If it's not part of an API, then there is no contract between the calling program or the library regarding the symbol's reliability or availability.  libjpeg-turbo is "backward API/ABI compatible with libjpeg v6b" (or v7 or v8, if you select that at compile time.)  That means that it supports the public libjpeg API.  Anything not part of the public API is an internal symbol, and there is no contract with the calling application regarding internal symbols.

To the best of my knowledge, our practices in this regard are consistent with those of other libraries.  So really you're just triggering on the code comment, but a code comment doesn't make something part of an API.

**Comment by dcommander** [comment] 2024-05-28 21:50
Continuing discussion under #767, since that refers specifically to FreeBSD.
