### ISSUE TITLE
Incorrect block smoothing for 2-block-wide progressive JPEGs

### ISSUE THREAD

**Issue by nigeltao** [libjpeg-turbo/libjpeg-turbo#700] opened 2023-06-25 06:13 UTC
`decompress_smooth_data` in `jdcoefct.c` interpolates a block's coefficients based on the surrounding blocks' DC coefficients.

"Surrounding" means at 0, ±1 or ±2 blocks away, vertically and horizontally. These are clamped at the edge of the image. Vertical clamping (for `next_block_row` at +1 and `next_next_block_row` at +2) are done by [this bit of code](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6b9e3b04008165260a13f77cf235170438d5adf8/jdcoefct.c#L557-L568):

```
if (block_row < block_rows - 1 || cinfo->output_iMCU_row < last_iMCU_row)
  next_block_row = buffer[block_row + 1] + cinfo->master->first_MCU_col[ci];
else
  next_block_row = buffer_ptr;

if (block_row < block_rows - 2 || cinfo->output_iMCU_row + 1 < last_iMCU_row)
  next_next_block_row = buffer[block_row + 2] + cinfo->master->first_MCU_col[ci];
else
  next_next_block_row = next_block_row;
```

---

Horizontal clamping is implemented slightly differently, since local variables are re-used from one iteration to the next. We'll focus on the center row (with local variables `DC11`, `DC12`, `DC13`, `DC14`, `DC15`) for the rest of this bug report.

There's [an overall initialization](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6b9e3b04008165260a13f77cf235170438d5adf8/jdcoefct.c#L575):

```
DC11 = DC12 = DC13 = DC14 = DC15 = (int)buffer_ptr[0][0];
```

Then [there's a loop](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6b9e3b04008165260a13f77cf235170438d5adf8/jdcoefct.c#L579-L581):

```
last_block_column = compptr->width_in_blocks - 1;
for (block_num = cinfo->master->first_MCU_col[ci];
     block_num <= cinfo->master->last_MCU_col[ci]; block_num++) {
  // Et cetera.
}
```

There's [a leading variables update](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6b9e3b04008165260a13f77cf235170438d5adf8/jdcoefct.c#L585-L599) at the top of the loop:

```
if (block_num == cinfo->master->first_MCU_col[ci] &&
    block_num < last_block_column) {
  DC14 = (int)buffer_ptr[1][0];
}
if (block_num + 1 < last_block_column) {
  DC15 = (int)buffer_ptr[2][0];
}
```

There's [a copy-the-variables update](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6b9e3b04008165260a13f77cf235170438d5adf8/jdcoefct.c#L787-L792) at the bottom of the loop:

```
/* Advance for next column */
DC11 = DC12;  DC12 = DC13;  DC13 = DC14;  DC14 = DC15;
```

---

For example, if the JPEG image is six blocks wide (call the columns a, b, c, d, e, f), so that `last_block_column` is 5, then the trace is:

```
DC11  DC12  DC13  DC14  DC15  Step
a*    a*    a*    a*    a*    Overall initialization
a     a     a     b*    c*    Leading variables update
a*    a*    b*    c*    c     Copy-the-variables update
a     a     b     c     d*    Leading variables update
a*    b*    c*    d*    d     Copy-the-variables update
a     b     c     d     e*    Leading variables update
c*    d*    e*    f*    f     Copy-the-variables update
b     c     d     e     f*    Leading variables update
c*    d*    e*    f*    f     Copy-the-variables update
c     d     e     f     f     Leading variables update
d*    e*    f*    f*    f     Copy-the-variables update
d     e     f     f     f     Leading variables update
```

Asterisks show an assignment. The actual "block smoothing" computations is based on the state after the "Leading variables updates", which looks good:

```
DC11  DC12  DC13  DC14  DC15  Step
a     a     a     b*    c*    Leading variables update
a     a     b     c     d*    Leading variables update
a     b     c     d     e*    Leading variables update
b     c     d     e     f*    Leading variables update
c     d     e     f     f     Leading variables update
d     e     f     f     f     Leading variables update
```

---

However, if the JPEG image is two blocks wide, so that `last_block_column` is 1 (and `DC15 = (int)buffer_ptr[2][0]` is never triggered), then the trace is:

```
DC11  DC12  DC13  DC14  DC15  Step
a*    a*    a*    a*    a*    Overall initialization
a     a     a     b*    a$    Leading variables update
a*    a*    b*    a*    a     Copy-the-variables update
a     a     b     a     a     Leading variables update
```

The dollar sign shows an incorrect lack-of-assignment (the "is never triggered"). Filtering on "Leading variables updates":

```
DC11  DC12  DC13  DC14  DC15  Step
a     a     a     b*    a$    Leading variables update
a     a     b     a     a     Leading variables update
```

The two rows are "aaaba" and "aabaa", both of which are wrong. They should be "aaabb" and "aabbb".

---

I think this tiny patch will fix it:

```diff
diff --git a/jdcoefct.c b/jdcoefct.c
index f33c931..fafa2b1 100644
--- a/jdcoefct.c
+++ b/jdcoefct.c
@@ -598,6 +598,12 @@ decompress_smooth_data(j_decompress_ptr cinfo, _JSAMPIMAGE output_buf)
           DC15 = (int)buffer_ptr[2][0];
           DC20 = (int)next_block_row[2][0];
           DC25 = (int)next_next_block_row[2][0];
+        } else {
+          DC05 = DC04;
+          DC10 = DC09;
+          DC15 = DC14;
+          DC20 = DC19;
+          DC25 = DC24;
         }
         /* If DC interpolation is enabled, compute coefficient estimates using
          * a Gaussian-like kernel, keeping the averages of the DC values.
```

**Comment by dcommander** [comment] 2023-06-29 22:16
Do you have a real image that demonstrates this issue?  Because I cannot reproduce it personally.  In my testing, `smoothing_ok()` returns `FALSE` when decompressing 2-block-wide progressive JPEG images.

**Comment by dcommander** [comment] 2023-07-03 22:15
@nigeltao Either answer my question, or I will be forced to close this issue.  I cannot reproduce the issue, and I cannot read your mind.

**Comment by nigeltao** [comment] 2023-07-05 05:19
I'm currently traveling. In terms of computers, I only have a phone. No laptop or desktop. I'll update the bug when I return.

**Comment by nigeltao** [comment] 2023-07-11 02:17
libjpeg-turbo's "block smoothing" only applies (1) to progressive (multiple scan) JPEG images when (2) the image is **partially** loaded. For example, a web browser might want to show some pixels when some but not all of a JPEG has been delivered over the network.

The `smoothing_ok` function will only return `TRUE` for **partially** loaded input. For fully loaded input (and well-formed progressive JPEG images), after the final scan, `coef_bits[coefi]` here will be zero.

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/jdcoefct.c#L413

---

"Partially loaded" is reproducible in a web browser, but web browsers are very complicated to build. Instead, we can reproduce with libjpeg-turbo's `djpeg` program, with this patch, and with an artificially truncated input:

```diff
diff --git a/jdcoefct.c b/jdcoefct.c
index 85cbcb79..7065094e 100644
--- a/jdcoefct.c
+++ b/jdcoefct.c
@@ -597,6 +597,7 @@ decompress_smooth_data(j_decompress_ptr cinfo, _JSAMPIMAGE output_buf)
           DC20 = (int)next_block_row[2][0];
           DC25 = (int)next_next_block_row[2][0];
         }
+fprintf(stderr, "DC1x values: %d %d %d %d %d\n", DC11, DC12, DC13, DC14, DC15);
         /* If DC interpolation is enabled, compute coefficient estimates using
          * a Gaussian-like kernel, keeping the averages of the DC values.
          *
```

- `infinity.ppm` (![infinity.ppm](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/8565232/e0ca7660-f0ca-4201-a7c6-37b3bc20ac76)) is a 12x8 image (a scaled version of https://simple.wikipedia.org/wiki/Infinity#/media/File:Infinite.svg). It's really a PPM file although GitHub's "upload a file" UI doesn't like filenames ending in `.ppm` so, as a workaround, I uploaded it as `infinity.ppm.jpg` but your browser might then render it as an "invalid JPEG".
- `infinity.jpg` (![infinity.jpg](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/8565232/f4faa21c-6850-446f-8991-dc352611046a)) is the result of `cjpeg -grayscale -progressive infinity.ppm > infinity.jpg` and, again, it is 12x8 pixels and hence 2 blocks wide. It has six scans: six `ff da` SOS (Start Of Scan) markers.
- `infinity.scan000.jpg` (![infinity.scan000.jpg](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/8565232/284e8377-a2b5-459a-9de1-8f97fc92053b)) truncates after the first scan (and then appending an `ff d9` EOI marker) to *simulate* "only partially loaded over the network".

---

`infinity.scan000.jpg` is the only one you need, for reproducing. In case you can't download it, here's a hex dump of it (and the original `infinity.ppm` that you can pass to `cjpeg`).

```
$ hd infinity.ppm
00000000  50 36 0a 31 32 20 38 0a  32 35 35 0a ff ff ff ff  |P6.12 8.255.....|
00000010  ff ff e6 e6 e6 d2 d2 d2  f2 f2 f2 ff ff ff ff ff  |................|
00000020  ff e8 e8 e8 c9 c9 c9 e8  e8 e8 ff ff ff ff ff ff  |................|
00000030  ff ff ff c0 c0 c0 36 36  36 20 20 20 59 59 59 e6  |......666   YYY.|
00000040  e6 e6 ce ce ce 3d 3d 3d  21 21 21 46 46 46 cc cc  |.....===!!!FFF..|
00000050  cc ff ff ff f2 f2 f2 59  59 59 86 86 86 be be be  |.......YYY......|
00000060  79 79 79 6c 6c 6c 41 41  41 4e 4e 4e c9 c9 c9 a3  |yyylllAAANNN....|
00000070  a3 a3 6c 6c 6c f4 f4 f4  d5 d5 d5 7a 7a 7a fa fa  |..lll......zzz..|
00000080  fa ff ff ff fa fa fa 58  58 58 27 27 27 db db db  |.......XXX'''...|
00000090  ff ff ff fd fd fd 83 83  83 d5 d5 d5 d5 d5 d5 83  |................|
000000a0  83 83 fd fd fd ff ff ff  dc dc dc 28 28 28 58 58  |...........(((XX|
000000b0  58 fa fa fa ff ff ff fb  fb fb 7b 7b 7b d4 d4 d4  |X.........{{{...|
000000c0  f3 f3 f3 6b 6b 6b a6 a6  a6 cc cc cc 50 50 50 40  |...kkk......PPP@|
000000d0  40 40 67 67 67 7e 7e 7e  c4 c4 c4 8c 8c 8c 5a 5a  |@@ggg~~~......ZZ|
000000e0  5a f2 f2 f2 ff ff ff ca  ca ca 45 45 45 23 23 23  |Z.........EEE###|
000000f0  3d 3d 3d ce ce ce e3 e3  e3 55 55 55 21 21 21 36  |===......UUU!!!6|
00000100  36 36 bf bf bf ff ff ff  ff ff ff ff ff ff e7 e7  |66..............|
00000110  e7 c9 c9 c9 e8 e8 e8 ff  ff ff ff ff ff f1 f1 f1  |................|
00000120  d0 d0 d0 e5 e5 e5 ff ff  ff ff ff ff              |............|
0000012c

$ hd infinity.scan000.jpg
00000000  ff d8 ff e0 00 10 4a 46  49 46 00 01 01 00 00 01  |......JFIF......|
00000010  00 01 00 00 ff db 00 43  00 08 06 06 07 06 05 08  |.......C........|
00000020  07 07 07 09 09 08 0a 0c  14 0d 0c 0b 0b 0c 19 12  |................|
00000030  13 0f 14 1d 1a 1f 1e 1d  1a 1c 1c 20 24 2e 27 20  |........... $.' |
00000040  22 2c 23 1c 1c 28 37 29  2c 30 31 34 34 34 1f 27  |",#..(7),01444.'|
00000050  39 3d 38 32 3c 2e 33 34  32 ff c2 00 0b 08 00 08  |9=82<.342.......|
00000060  00 0c 01 01 11 00 ff c4  00 14 00 01 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 05 ff da 00 08  |................|
00000080  01 01 00 00 00 01 5d 4f  ff d9                    |......]O..|
0000008a
```

---

Running our patched `djpeg` on this `infinity.scan000.jpg` file prints:

```
$ ./djpeg infinity.scan000.jpg > /dev/null
DC1x values: 46 46 46 86 46
DC1x values: 46 46 86 46 46
```

This demonstrates the incorrect `aaaba, aabaa` pattern instead of the correct `aaabb, aabbb` pattern.

**Closed** 2023-08-03 19:47 UTC
Labels: bug
