### ISSUE TITLE
Possible regression in jpegtran 2.0.2 for custom scan script

### ISSUE THREAD

**Issue by muelleme** [libjpeg-turbo/libjpeg-turbo#335] opened 2019-02-25 10:06 UTC
Hi,

I came across some very weird behaviour using jpegtran in version `2.0.2` (built from source on Ubuntu 18.04 LTS).

If I use `-scans` to transform a baseline JPEG into a progressive one, and my scan script contains a scan performing spectral selection including exactly the first 16 AC coefficients (for any channel), then jpegtran fails with `Missing Huffman code table entry` on literally every image I tested.

Here is a scan script to reproduce:

```
0 1 2: 0 0 0 0;
0: 1 16 0 0;
0: 17 63 0 0;
1: 1 63 0 0;
2: 1 63 0 0;
```

Invocation of jpegtran to reproduce:

```
$ jpegtran -copy all -scans test.scan lena10.jpg > /dev/null
Missing Huffman code table entry
```

Replacing the 16 with any other number seems to fix the issue.
The same scan script works fine with version `1.5.3` (also build from source).

**Comment by dcommander** [comment] 2019-02-25 17:16
Confirmed.  I used `git bisect` to determine the regression point: 5b177b3cab5cfb661256c1e74df160158ec6c34e
(NOTE: In the future, it would help me tremendously if you would do that yourself prior to reporting the regression.)

@mayeut, this is a regression caused by the SSE2-accelerated progressive Huffman encoder.  Can you look into it?

**Comment by dcommander** [comment] 2019-07-11 22:10
Given that the author of the code isn't responding and libjpeg-turbo funding is exhausted through August, marking as "funding needed."

**Closed** 2019-08-15 03:09 UTC
Labels: bug, funding needed
