### ISSUE TITLE
It seems wrong targeted  binary for iOS.

### ISSUE THREAD

**Issue by ryutei** [libjpeg-turbo/libjpeg-turbo#422] opened 2020-04-17 07:46 UTC
Hello.
Official Binaries says libjpeg-turbo support iOS simulator.
 
> libjpeg-turbo 2.1.x and later:
> iOS 7.0 and later / ARMv8 w/ bitcode (iPhone 5S and later, iPad Mini 2 and later, iPad Air)
> iOS 7.0 and later / i386 and x86-64 w/o bitcode (iOS simulator)

But when I build my project that linked with libjpeg-turbo 2.0.4, Xcode 11 reports error.
> Target Integrity
> Building for iOS Simulator, but the linked library libturbojpeg.a was built for macOS + iOS.

Is it correct that this appears to be built for Mac Catalyst, not for iOS Simulator? (I don't know detail between Simulator and Catalyst.)

**Comment by dcommander** [comment] 2020-04-17 18:10
Duplicate of #406.  Please refer to the discussion in that issue, and please use the dev/2.1 evolving pre-release build (https://libjpeg-turbo.org/DeveloperInfo/PreReleases) in order to get proper iOS simulator support.  libjpeg-turbo 2.1 builds a separate package for this (libjpeg-turbo-{version}-ios.dmg.)

**Closed by dcommander** 2020-04-17 18:10 UTC
