### ISSUE TITLE
jag/stairs-like effect 

### ISSUE THREAD

**Issue by NE21** [libjpeg-turbo/libjpeg-turbo#145] opened 2017-03-23 21:12 UTC
I'm sorry if my questions needs to be more specific. But I'm wondering what can be the cause of a jag/stair like effect in the output jpeg. We noticed that changing the width slightly fixes/causes the issue, we also noticed that for certain image sizes this jag was fixed going from libjpeg-turbo 1.4.2 to 1.5.1.

**Comment by dcommander** [comment] 2017-03-23 21:30
Yes, you need to be more specific. Your comment suggests that you are trying to use decompression scaling, so I need to know exactly how you are decompressing the JPEG. Show me a code snippet, and tell me what size the JPEG image is.

**Comment by dcommander** [comment] 2017-03-29 16:32
Please provide the requested information if you want help with this.  Otherwise I will be forced to close the issue.  I cannot read your mind.

**Comment by NE21** [comment] 2017-03-29 16:45
Thank you for the quick responses. I'm still looking into what can be causing this issue on our part. I openned this issue because I was looking for ideas on what can trigger this behavior (do we need padding .. etc) but it's probably our use of it that is incorrect.. Please close the issue for now and if I find otherwise I will let you know.

**Comment by dcommander** [comment] 2017-03-29 16:51
OK, well, I could probably answer the question in 10 seconds if you provided the information I asked, but whatever.  I strongly suspect that what you're observing is expected behavior caused by the decompression scaling feature.

**Closed by dcommander** 2017-03-29 16:51 UTC
