### ISSUE TITLE
Public headers pollute global namespace with HAVE_STDLIB_H, etc.

### ISSUE THREAD

**Issue by debarshiray** [libjpeg-turbo/libjpeg-turbo#280] opened 2018-09-11 05:36 UTC
After installing libjpeg-turbo-2.0.0, `/usr/include/jconfig-64.h` defines `HAVE_STDLIB_H` and similar macros. These pollute the global namespace because they can conflict with library users' own definition of those macros. eg., Autotools projects get similarly named macros in their `config.h`, and every `#include <config.h>` in their *.c files will lead to a warning:
```
../config.h:48: warning: "HAVE_STDLIB_H" redefined
 #define HAVE_STDLIB_H 1
```

If these must be exported then they should have an appropriate namespace prefix.

**Comment by dcommander** [comment] 2018-09-11 16:55
The warning represents a regression relative to libjpeg-turbo 1.5.x, and it was fixed in 2260b66e1671038a362dca4a204c28d72b8f7e4e.  As far as including `HAVE_STDLIB_H` and similar macros in jconfig.h, those have existed in libjpeg's jconfig.h for decades.  On a couple of occasions, I've tried to remove some of the legacy macros from our public headers, but I discovered that, unfortunately, there is some software out there that relies on those legacy macros, and removing them caused that software to break.  So the best I can do about this is to restore Autotools compatibility in jconfig.h, which was done in 2260b66e1671038a362dca4a204c28d72b8f7e4e.  Refer to #275.

**Closed by dcommander** 2018-09-11 16:55 UTC

**Comment by debarshiray** [comment] 2018-09-11 17:18
If 2260b66e1671038a362dca4a204c28d72b8f7e4e silences the warning, then great!

Regardless, exposing HAVE_STDLIB_H and such in the public headers is still a bug because it pollutes the global namespace. Unless HAVE_STDLIB_H and friends are part of libjpeg's API guarantees, which would be wrong in itself, shouldn't those who rely on them being defined be asked to fix their code.

**Comment by dcommander** [comment] 2018-09-11 17:55
- Those macros have existed in the libjpeg public headers for at least 24 years, and they continue to exist in the libjpeg v9c public headers.  Given that the original intent of this project was to act as a drop-in replacement for libjpeg v6b, there are some incorrect-but-canonical behaviors that I would love to change but can't without breaking backward compatibility.  And yes, I agree with you that downstream projects should never rely on legacy macros from our public headers, but unfortunately, that's not the way it works.  The way it works is:  I put out a new release of libjpeg-turbo that "fixes" these incorrect behaviors in our code, but it breaks someone's downstream build, and they blame me for that.  Since their build may have worked fine for decades, it becomes my problem to fix it.  That happened twice when I tried to eliminate the `FAR` and `JMETHOD()` macros, which libjpeg-turbo never needed (those macros were, respectively, only needed for MS-DOS systems and non-ANSI compilers.)
- As far as namespace pollution, that is just a by-product of the fact that `HAVE_*_H` are commonly used by Autotools.  You could just as easily argue that *any* macro defined in our public headers has the potential to pollute a downstream namespace, if the downstream project happens to use a macro with the same name.
- A quick search of /usr/include reveals that we are not the only project that defines these macros.  So, yes, we need to be defining them in the same way that Autotools defines them, which is also the same way that libjpeg-turbo 1.5.x and prior defined them.  But there isn't really a strong argument to be made for eliminating them from our headers.

For matters such as this, just please accept that this project has a ton of legacy attached to it.  The libjpeg API is brittle and esoteric and fine-grained and very difficult to expand in a backward-compatible way, but it's also canonical, and at this point, its imperfections are canonical as well.  Those desiring a more legacy-free API can always use TurboJPEG, which is slowly but surely gaining most of the relevant features from the libjpeg API.

**Comment by debarshiray** [comment] 2018-09-12 07:41
Thanks for the explanation. I understand where you are coming from.

I wonder, if someone is actually relying on the presence of `HAVE_STDLIB_H`, then surely they must have a fallback for cases when that macro is absent (ie. they care about building without `stdlib.h`). If libjpeg-turbo was to drop `HAVE_STDLIB_H` from it's public headers, then it might break the assumption that it's tied to the presence of `stdlib.h`, but their builds should still hobble along. Or am I missing something?

> You could just as easily argue that any macro defined in our public headers
> has the potential to pollute a downstream namespace, if the downstream project
> happens to use a macro with the same name.

It would be fine if the names were suitably prefixed.

Anyway, thanks for your time!

**Comment by dcommander** [comment] 2018-09-12 16:40
My basic position is:  those macros have existed in the libjpeg public headers for at least 24 years, they have existed in the libjpeg-turbo public headers all along, and they continue to exist in libjpeg.  They also exist in public headers from other OSS projects.

I do agree that, ideally, those macros should not exist in our public headers (or anyone else's), but libjpeg-turbo has millions of users at this point and has many touch points throughout the open source community, so my default answer for any change proposals has to be "do nothing."  In other words, the burden of proof is on the prosecution.  :)  If someone wants a different answer, then they have to justify the change proposal in terms of risk vs. reward.  In this case, literally no one noticed the presence of those macros in our headers for the eight years prior to libjpeg-turbo 2.0.0, and apparently no one has ever noticed the presence of those macros in the libjpeg headers either, so barring the regression that was introduced with the new build system in libjpeg-turbo 2.0.0, I consider the risk of keeping those macros to be approximately zero.  The risk of removing them may be small but is not zero, so in my mind, that change is not justified unless it can be shown to eliminate some other user-visible issue.
